import { Room } from "@/types/room";
export const rooms: Room[] = [
  {
    id: 1,
    title: "숫자 규칙 추리",
    question: "다음 수는 무엇일까요? 3, 6, 11, 18, ?",
    answer: "27",
    hint: "숫자 사이의 차이를 확인해보세요.+3, +5 ....",
    type: "number_pattern",
    difficulty: 3,
  },
  {
    id: 2,
    title: "OX 퀴즈",
    question: "고래는 물고기다. (O/X)",
    answer: "X",
    hint: "고래의 생물학적 분류를 생각해보세요.",
    type: "ox_quiz",
    difficulty: 4,
  },
  {
    id: 3,
    title: "순서 정렬",
    question:
      "다음 동물들 중 가장 빠른 동물을 고르세요: [돛새치], [참치], [상어], [돌고래]",
    answer: "돛새치",
    hint: "시속 110km 이상으로 헤엄칠 수 있는 물고기를 찾아보세요.",
    type: "drag_sort",
    difficulty: 4.5,
  },
  {
    id: 4,
    title: "시저 암호 해독",
    question: "ujhfs",
    answer: "tiger",
    hint: "알파벳을 한 글자씩 뒤로 옮겨보세요.",
    type: "cipher",
    difficulty: 5,
  },
  {
    id: 5,
    title: "거울 문자 해독",
    question: "글자를 읽어보세요: ƨpiʜɔ oƚɒƚoq",
    answer: "potato chips",
    hint: "글자를 거울에 비춰보세요.",
    type: "mirror_text",
    difficulty: 5.5,
  },
  {
    id: 6,
    title: "이미지 해독",
    question: "방을 잘 관찰해보세요. 답은한글로..",
    answer: "프랑스",
    hint: "어떤 나라의 이름일까요?",
    type: "direction_sequence",
    difficulty: 6,
  },
  {
    id: 7,
    title: "그림 해독",
    question: "비밀번호 4자리를 찾아보세요.",
    answer: "1461",
    hint: "day",
    type: "image_difference",
    difficulty: 6.5,
  },
  {
    id: 8,
    title: "단어 조합",
    question: "trnapoeimuapn ??",
    answer: "tree",
    hint: "글자가 섞여 있습니다.",
    type: "word_unscramble",
    difficulty: 7.5,
  },
  {
    id: 9,
    title: "글자 자물쇠",
    question: "숫자를 찾고 글자를 찾아보세요.",
    answer: "NOX",
    hint: "모든 메모를 읽어보세요.",
    type: "number_lock",
    difficulty: 8.5,
  },
  {
    id: 10,
    title: "색깔 퍼즐",
    question: "🟥 = 3, 🟩🟩 = 8, 🟦 + 🟥 = 6. 암호는?",
    answer: "3434",
    hint: "색을 숫자로 바꾸고 조합해보세요.",
    type: "color_logic",
    difficulty: 10,
  },
];
