import 'server-only';
import { Room } from '@/types/room';

// Type mix guideline: docs/superpowers/specs/2026-07-04-level-system-and-puzzle-content-design.md
// Level 1 (id 1~30) was rewritten on 2026-08-26 to replace generic escape-room
// tropes (Caesar shift, A=1..Z=26, SOS morse, "3 people one lies") with fresher
// scenarios and, where requested, fresher solving logic (constraint-based seating/
// ordering puzzles instead of liar puzzles). Levels 2~4 are unchanged from the
// original content pass and still carry the "규칙추리" label quirk and liar-puzzle
// template noted in git history.
export const rooms: Room[] = [
	// ==========================================
	// Level 1 (10대 / 초등 고학년 수준) — 방 1~30
	// ==========================================
	{
		id: 1,
		title: '자정의 종소리',
		question: '[저택의 기록]\n탑 위 낡은 벽시계는 정오까지 매 시각 정각마다 그 시각 숫자만큼 종을 울린다.\n1시엔 1번, 2시엔 2번... 이런 식으로 12시까지 울린다면,\n정오까지 울린 종소리는 모두 몇 번인가? (숫자만 입력)',
		answer: '78',
		hint: '1부터 12까지의 숫자를 모두 더해보세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
		variants: [
			{
				variantId: '1-a',
				title: '자정의 종소리',
				question: '[저택의 기록]\n탑 위 낡은 벽시계는 정오까지 매 시각 정각마다 그 시각 숫자만큼 종을 울린다.\n1시엔 1번, 2시엔 2번... 이런 식으로 12시까지 울린다면,\n정오까지 울린 종소리는 모두 몇 번인가? (숫자만 입력)',
				answer: '78',
				hint: '1부터 12까지의 숫자를 모두 더해보세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
			{
				variantId: '1-b',
				title: '온실의 작은 시계',
				question: '[온실의 기록]\n지하 온실의 작은 시계는 1시부터 6시까지만 표시되며, 매 시각 정각마다 그 숫자만큼 종을 울린다.\n1시부터 6시까지 울린 종소리는 모두 몇 번인가? (숫자만 입력)',
				answer: '21',
				hint: '1부터 6까지의 숫자를 모두 더해보세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
			{
				variantId: '1-c',
				title: '다락방의 뻐꾸기시계',
				question: '[다락방의 기록]\n다락방 뻐꾸기시계는 1시부터 10시까지 표시되며, 매 시각 정각마다 그 숫자만큼 울음을 운다.\n1시부터 10시까지 운 횟수는 모두 몇 번인가? (숫자만 입력)',
				answer: '55',
				hint: '1부터 10까지의 숫자를 모두 더해보세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
		],
	},
	{
		id: 2,
		title: '다과회 접시',
		question: '[응접실의 기록]\n오늘 다과회에 쿠키 37개가 나왔다.\n손님 5명에게 최대한 똑같이 나누어 준다면, 한 명이 받는 쿠키는 몇 개인가?\n(남는 쿠키는 세지 않는다, 숫자만 입력)',
		answer: '7',
		hint: '37을 5로 나눈 몫을 구하세요.',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
		variants: [
			{
				variantId: '2-a',
				title: '다과회 접시',
				question: '[응접실의 기록]\n오늘 다과회에 쿠키 37개가 나왔다.\n손님 5명에게 최대한 똑같이 나누어 준다면, 한 명이 받는 쿠키는 몇 개인가?\n(남는 쿠키는 세지 않는다, 숫자만 입력)',
				answer: '7',
				hint: '37을 5로 나눈 몫을 구하세요.',
				type: '연산',
				difficulty: 1,
				inputType: 'number',
			},
			{
				variantId: '2-b',
				title: '오렌지 바구니',
				question: '[부엌의 기록]\n바구니에 오렌지 29개가 담겨 있다.\n손님 4명에게 최대한 똑같이 나누어 준다면, 한 명이 받는 오렌지는 몇 개인가?\n(남는 오렌지는 세지 않는다, 숫자만 입력)',
				answer: '7',
				hint: '29를 4로 나눈 몫을 구하세요.',
				type: '연산',
				difficulty: 1,
				inputType: 'number',
			},
			{
				variantId: '2-c',
				title: '사탕 병',
				question: '[부엌의 기록]\n유리병에 사탕 53개가 들어 있다.\n손님 6명에게 최대한 똑같이 나누어 준다면, 한 명이 받는 사탕은 몇 개인가?\n(남는 사탕은 세지 않는다, 숫자만 입력)',
				answer: '8',
				hint: '53을 6으로 나눈 몫을 구하세요.',
				type: '연산',
				difficulty: 1,
				inputType: 'number',
			},
		],
	},
	{
		id: 3,
		title: '두 자루의 초',
		question: '[지하실의 기록]\n초 A는 다 타는 데 40분이 걸리고, 초 B는 25분이 걸린다.\n두 초에 동시에 불을 붙였다면, 초 B가 먼저 다 탄 뒤 몇 분이 지나야 초 A도 다 타는가? (숫자만 입력)',
		answer: '15',
		hint: '두 초가 다 타는 데 걸리는 시간의 차이를 구하세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
		variants: [
			{
				variantId: '3-a',
				title: '두 자루의 초',
				question: '[지하실의 기록]\n초 A는 다 타는 데 40분이 걸리고, 초 B는 25분이 걸린다.\n두 초에 동시에 불을 붙였다면, 초 B가 먼저 다 탄 뒤 몇 분이 지나야 초 A도 다 타는가? (숫자만 입력)',
				answer: '15',
				hint: '두 초가 다 타는 데 걸리는 시간의 차이를 구하세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
			{
				variantId: '3-b',
				title: '창고의 초',
				question: '[보관실의 기록]\n초 C는 다 타는 데 50분이 걸리고, 초 D는 30분이 걸린다.\n두 초에 동시에 불을 붙였다면, 초 D가 먼저 다 탄 뒤 몇 분이 지나야 초 C도 다 타는가? (숫자만 입력)',
				answer: '20',
				hint: '두 초가 다 타는 데 걸리는 시간의 차이를 구하세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
			{
				variantId: '3-c',
				title: '탑의 초',
				question: '[탑의 기록]\n초 E는 다 타는 데 45분이 걸리고, 초 F는 18분이 걸린다.\n두 초에 동시에 불을 붙였다면, 초 F가 먼저 다 탄 뒤 몇 분이 지나야 초 E도 다 타는가? (숫자만 입력)',
				answer: '27',
				hint: '두 초가 다 타는 데 걸리는 시간의 차이를 구하세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
		],
	},
	{
		id: 4,
		title: '정원사의 발걸음',
		question: '[정원의 기록]\n정원사는 하루에 정원을 3바퀴씩 돌며, 한 바퀴에 120걸음을 걷는다.\n그가 5일 동안 걸은 걸음 수는 모두 몇 걸음인가? (숫자만 입력)',
		answer: '1800',
		hint: '하루에 걷는 걸음 수(3 x 120)를 구한 뒤 5를 곱하세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
		variants: [
			{
				variantId: '4-a',
				title: '정원사의 발걸음',
				question: '[정원의 기록]\n정원사는 하루에 정원을 3바퀴씩 돌며, 한 바퀴에 120걸음을 걷는다.\n그가 5일 동안 걸은 걸음 수는 모두 몇 걸음인가? (숫자만 입력)',
				answer: '1800',
				hint: '하루에 걷는 걸음 수(3 x 120)를 구한 뒤 5를 곱하세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
			{
				variantId: '4-b',
				title: '집사의 순찰',
				question: '[복도의 기록]\n집사는 하루에 저택 복도를 4바퀴씩 돌며, 한 바퀴에 150걸음을 걷는다.\n그가 4일 동안 걸은 걸음 수는 모두 몇 걸음인가? (숫자만 입력)',
				answer: '2400',
				hint: '하루에 걷는 걸음 수(4 x 150)를 구한 뒤 4를 곱하세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
			{
				variantId: '4-c',
				title: '하녀의 계단질',
				question: '[계단의 기록]\n하녀는 하루에 계단을 2바퀴씩 오르내리며, 한 바퀴에 90걸음을 걷는다.\n그녀가 7일 동안 걸은 걸음 수는 모두 몇 걸음인가? (숫자만 입력)',
				answer: '1260',
				hint: '하루에 걷는 걸음 수(2 x 90)를 구한 뒤 7을 곱하세요.',
				type: '연산',
				difficulty: 2,
				inputType: 'number',
			},
		],
	},
	{
		id: 5,
		title: '책 상자의 무게',
		question: '[서재의 기록]\n나무 상자 안에 책 12권이 들어 있다. 책 한 권의 무게는 250g이고, 빈 상자의 무게는 300g이다.\n책이 담긴 상자 전체의 무게는? (숫자만 입력, g 단위)',
		answer: '3300',
		hint: '책 12권의 무게(250 x 12)를 구한 뒤 상자 무게 300을 더하세요.',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 6,
		title: '만찬 식기',
		question: '[식당의 기록]\n오늘 만찬에 손님 8명이 초대되었다.\n손님 한 명당 접시 1개, 국그릇 1개, 잔 2개가 필요하다.\n필요한 식기는 모두 몇 개인가? (숫자만 입력)',
		answer: '32',
		hint: '한 명당 필요한 식기 수(1+1+2)를 구한 뒤 8을 곱하세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 7,
		title: '정오의 그림자',
		question: '[정원의 기록]\n정오 무렵 해는 남쪽 하늘 높이 떠 있다.\n이때 정원 조각상의 그림자는 어느 방향을 향하는가? (동/서/남/북 중 입력)',
		answer: '북',
		hint: '그림자는 해가 있는 방향의 반대쪽으로 생깁니다.',
		type: '관찰',
		difficulty: 1,
	},
	{
		id: 8,
		title: '기울어가는 해',
		question: '[정원의 기록]\n정오에는 나무 그림자가 매우 짧다. 해가 서쪽으로 기울어 오후 5시가 되면\n나무 그림자는 정오보다 길어지는가, 짧아지는가? (길어진다/짧아진다 중 입력)',
		answer: '길어진다',
		hint: '해가 지평선에 가까워질수록 그림자는 길게 늘어집니다.',
		type: '관찰',
		difficulty: 1,
	},
	{
		id: 9,
		title: '거울 속 시계',
		question: '[응접실의 기록]\n벽걸이 거울에 비친 시계는 3시 정각을 가리키는 것처럼 보인다.\n거울에 비치지 않은 실제 시계가 가리키는 시각은 몇 시인가? (숫자만 입력)',
		answer: '9',
		hint: '거울에 비친 시각과 실제 시각을 더하면 12시가 됩니다.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 10,
		title: '정원 울타리',
		question: '[정원의 기록]\n일직선 울타리에 기둥이 일정한 간격으로 박혀 있다. 양 끝에도 기둥이 있고,\n기둥 사이의 간격은 모두 11개다. 울타리 기둥은 모두 몇 개인가? (숫자만 입력)',
		answer: '12',
		hint: '간격의 수보다 기둥의 수가 1개 더 많습니다.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 11,
		title: '오르골의 음',
		question: '[음악실의 기록]\n낡은 오르골에 도=1, 레=2, 미=3, 파=4, 솔=5, 라=6, 시=7이라 적힌 쪽지가 붙어 있다.\n오르골이 연주한 음 "미, 도, 솔"의 숫자를 모두 더하면? (숫자만 입력)',
		answer: '9',
		hint: '미=3, 도=1, 솔=5를 더하세요.',
		type: '암호',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 12,
		title: '스테인드글라스 창',
		question: '[탑의 기록]\n창문 유리 조각에 빨강=2, 파랑=5, 노랑=3이라는 숫자가 매겨져 있다.\n이 창문은 빨간 유리 3장, 파란 유리 2장, 노란 유리 1장으로 이루어져 있다.\n(빨간 유리 수 x 2) + (파란 유리 수 x 5) + (노란 유리 수 x 3)의 값은? (숫자만 입력)',
		answer: '19',
		hint: '3x2=6, 2x5=10, 1x3=3을 모두 더하세요.',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 13,
		title: '손수건의 매듭',
		question: '[다락방의 기록]\n손수건에 매듭이 세 묶음으로 묶여 있다: 4개, 15개, 7개.\n매듭 개수를 알파벳 순서(1=A)로 바꾸어 순서대로 읽으면 어떤 영어 단어가 되는가? (대문자 3글자)',
		answer: 'DOG',
		hint: '4번째, 15번째, 7번째 알파벳을 찾아보세요.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 14,
		title: '안내판의 문구',
		question: '[복도의 기록]\n복도 안내판에 네 개의 낡은 단어가 세로로 적혀 있다.\n"Old / Peaceful / Empty / Nights"\n각 단어의 첫 글자만 위에서부터 순서대로 읽으면 어떤 단어가 되는가? (대문자 4글자)',
		answer: 'OPEN',
		hint: '각 줄의 맨 앞 글자만 모아보세요.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 15,
		title: '낡은 타자기',
		question: '[서재의 기록]\n타자기 자판 중 유독 진하게 눌린 자국이 있는 키 세 개: Y, K, E.\n이 세 글자를 "열쇠"를 뜻하는 올바른 영어 단어 순서로 배열하면? (대문자 3글자)',
		answer: 'KEY',
		hint: '"열쇠"를 뜻하는 세 글자 영단어입니다.',
		type: '암호',
		difficulty: 1,
	},
	{
		id: 16,
		title: '만찬 좌석',
		question: '[식당의 기록]\n식탁 자리 1~4번(1번이 문 쪽, 4번이 창가 쪽) 중 A, B, C, D가 앉는다.\n① B는 4번(창가) 자리에 앉는다.\n② D는 3번 자리에 앉는다.\n③ C는 1번 자리에 앉지 않는다.\nA는 몇 번 자리에 앉는가? (숫자만 입력)',
		answer: '1',
		hint: '남은 자리는 1번과 2번뿐입니다. C가 1번이 아니라면 C는 2번, A는 1번입니다.',
		type: '추리',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 17,
		title: '하인들의 오후',
		question: '[복도의 기록]\n요리사, 집사, 정원사가 각각 다른 시간에 청소를 마쳤다.\n① 정원사는 세 사람 중 가장 마지막에 끝냈다.\n② 집사는 두 번째로 끝났다.\n가장 먼저 청소를 끝낸 사람은 누구인가? (요리사/집사/정원사 중 입력)',
		answer: '요리사',
		hint: '정원사=마지막, 집사=두 번째이므로 남은 사람이 첫 번째입니다.',
		type: '추리',
		difficulty: 1,
	},
	{
		id: 18,
		title: '보석 상자 저울질',
		question: '[보관실의 기록]\n상자 A, B, C, D의 무게를 저울로 비교했다.\n① A는 B보다 무겁다.\n② B는 C보다 무겁다.\n③ C는 D보다 무겁다.\n네 상자 중 가장 무거운 것은? (A/B/C/D 중 입력)',
		answer: 'A',
		hint: 'A>B>C>D 순서가 됩니다.',
		type: '추리',
		difficulty: 2,
	},
	{
		id: 19,
		title: '손님방 배정',
		question: '[복도의 기록]\n객실 101, 102, 103, 104호에 톰, 제인, 폴, 마리가 묵는다.\n① 톰은 101호에 묵는다.\n② 제인은 톰 바로 옆 방(102호)에 묵는다.\n③ 마리는 104호에 묵지 않는다.\n④ 남은 두 방(103, 104호)에는 폴과 마리가 묵는다.\n폴은 몇 호에 묵는가? (숫자만 입력)',
		answer: '104',
		hint: '마리가 104호가 아니라면 마리는 103호, 폴은 104호입니다.',
		type: '추리',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 20,
		title: '편지 봉인',
		question: '[서재의 기록]\n편지를 완성하는 과정 조각들을 순서대로 탭하시오.',
		answer: '편지쓰기봉투에넣기촛농으로봉인우표붙이기',
		hint: '쓰고, 담고, 봉하고, 붙이는 순서를 생각하세요.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['편지쓰기', '봉투에넣기', '촛농으로봉인', '우표붙이기'],
	},
	{
		id: 21,
		title: '차 한 잔',
		question: '[응접실의 기록]\n차를 우리는 과정 조각들을 순서대로 탭하시오.',
		answer: '찻잎넣기물붓기기다리기따르기',
		hint: '찻잎을 넣고, 물을 붓고, 기다린 뒤, 따르는 순서입니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['찻잎넣기', '물붓기', '기다리기', '따르기'],
	},
	{
		id: 22,
		title: '온실의 새싹',
		question: '[온실의 기록]\n식물이 자라나는 순서 조각들을 순서대로 탭하시오.',
		answer: '씨앗새싹줄기꽃',
		hint: '가장 작은 상태부터 순서대로 고르세요.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['씨앗', '새싹', '줄기', '꽃'],
	},
	{
		id: 23,
		title: '초상화 손질',
		question: '[다락방의 기록]\n낡은 초상화를 손질하는 과정 조각들을 순서대로 탭하시오.',
		answer: '먼지털기세척하기건조하기액자걸기',
		hint: '털고, 씻고, 말리고, 거는 순서입니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['먼지털기', '세척하기', '건조하기', '액자걸기'],
	},
	{
		id: 24,
		title: '저택의 하루',
		question: '[탑의 기록]\n저택의 하루가 흘러가는 순서 조각들을 순서대로 탭하시오.',
		answer: '해뜸종울림식사시간해짐',
		hint: '아침부터 밤까지의 순서를 떠올려보세요.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['해뜸', '종울림', '식사시간', '해짐'],
	},
	{
		id: 25,
		title: '거꾸로 도는 시계',
		question: '[복도의 기록]\n하인은 매일 아침 저택의 모든 시계를 일부러 반대로(거울에 비친 모습처럼) 돌려놓는다.\n그 이유는 무엇일까? (고장이라서/거울방때문에/장난이라서 중 입력)',
		answer: '거울방때문에',
		hint: '이 저택엔 사방이 거울로 된 방이 있습니다. 거울에 비치면 시계가 다시 제대로 보이겠죠.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 26,
		title: '그림자 쓸기',
		question: '[정원의 기록]\n정원사는 매일 오후, 나무 그림자가 길어질 때마다 그 그림자를 정성껏 빗자루로 쓸어낸다.\n그 이유는 무엇일까? (그림자가무거워서/발자국을숨기려/전통이라서 중 입력)',
		answer: '발자국을숨기려',
		hint: '그림자 위에 남는 건 나무 그림자만이 아닙니다.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 27,
		title: '빈 소금 단지',
		question: '[부엌의 기록]\n주방 선반에는 소금 단지가 두 개 있는데, 하나는 항상 비어 있다.\n그 이유는 무엇일까? (열쇠를숨기려고/장식용이라서/소금이비싸서 중 입력)',
		answer: '열쇠를숨기려고',
		hint: '텅 빈 단지 속을 들여다본 사람은 아직 없습니다.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 28,
		title: '정원 두 바퀴',
		question: '[정원의 기록]\n정사각형 정원의 한 변은 5m다.\n이 정원 둘레를 두 바퀴 돈다면 모두 몇 m를 걷는 것인가? (숫자만 입력)',
		answer: '40',
		hint: '한 바퀴 둘레(5 x 4)를 구한 뒤 2배 하세요.',
		type: '도형',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 29,
		title: '탑의 육각창',
		question: '[탑의 기록]\n탑의 창문은 정육각형 모양이다.\n창틀의 각 변마다 촛불을 하나씩 세우려면 촛불은 몇 개 필요한가? (숫자만 입력)',
		answer: '6',
		hint: '정육각형의 변은 몇 개인가요?',
		type: '도형',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 30,
		title: '계단의 삼각 장식',
		question: '[계단의 기록]\n계단 옆 벽에 삼각형 장식이 3단으로 쌓여 있다.\n위에서부터 1개, 3개, 5개가 놓여 있다면 삼각형 장식은 모두 몇 개인가? (숫자만 입력)',
		answer: '9',
		hint: '1 + 3 + 5를 계산하세요.',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	// ==========================================
	// Level 2 (20대 / 중학교 1학년 수준) — 방 31~60
	// Rewritten on 2026-08-26 alongside Level 1: fresh scenarios and, where the
	// original leaned on a cliché (Caesar +3 shift, A=1..Z=26, binary number,
	// "3 people one lies" x3), fresh solving logic too.
	// ==========================================
	{
		id: 31,
		title: '저택 관리비 인상',
		question: '[사무실의 기록]\n이번 달 관리비는 지난달보다 20% 올랐다.\n지난달 관리비가 35만원이었다면 이번 달은 얼마인가? (숫자만 입력, 만원 단위)',
		answer: '42',
		hint: '35에 20%(0.2)를 곱한 값을 35에 더하세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 32,
		title: '일차식 자물쇠',
		question: '[서재의 기록]\n자물쇠 다이얼 규칙: 3x - 4 = 20.\nx의 값은? (숫자만 입력)',
		answer: '8',
		hint: '양변에 4를 더하고 3으로 나누세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 33,
		title: '액자 속 비율',
		question: '[서재의 기록]\n액자의 세로:가로 비율은 4:5이다.\n세로가 24cm라면 가로는 몇 cm인가? (숫자만 입력)',
		answer: '30',
		hint: '24를 4로 나눈 뒤 5를 곱하세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 34,
		title: '녹아내리는 양초',
		question: '[보관실의 기록]\n양초의 길이는 34cm이고, 매 시간 3cm씩 녹는다.\n6시간 후 남은 길이는? (숫자만 입력)',
		answer: '16',
		hint: '34에서 (3 x 6)을 빼세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 35,
		title: '저택의 화폐',
		question: '[사무실의 기록]\n이 저택에서만 쓰는 옛 화폐 1골드는 1200원과 같다.\n7골드는 몇 원인가? (숫자만 입력)',
		answer: '8400',
		hint: '1200 x 7',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 36,
		title: '지상층과 지하층',
		question: '[탑의 기록]\n탑의 지하층 계단 수는 지상층 계단 수의 3배다.\n지하층 계단이 42개라면 지상층 계단은 몇 개인가? (숫자만 입력)',
		answer: '14',
		hint: '42를 3으로 나누세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 37,
		title: '보물 지도의 좌표',
		question: '[정원의 기록]\n보물 지도 위 표시는 (3, 4)다. 이 위치에서 동쪽으로 2칸(x좌표 +2), 북쪽으로 1칸(y좌표 +1) 이동했다.\n이동한 위치의 x좌표와 y좌표를 더한 값은? (숫자만 입력)',
		answer: '10',
		hint: '새 좌표는 (5, 5)입니다. 두 수를 더하세요.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 38,
		title: '갈림길의 맞꼭지각',
		question: '[정원의 기록]\n정원의 두 오솔길이 갈림길에서 만나 한쪽 각이 60도를 이룬다.\n그 각의 맞은편(맞꼭지각)에 생기는 각도는? (숫자만 입력)',
		answer: '60',
		hint: '맞꼭지각의 크기는 항상 서로 같습니다.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 39,
		title: '탑 높이 재기',
		question: '[탑의 기록]\n탑 꼭대기에서 돌을 던지자 3초 후 바닥에 닿는 소리가 들렸다.\n소리는 1초에 340m를 이동한다. 소리가 이동한 거리를 탑의 높이로 어림잡으면 몇 m인가? (숫자만 입력)',
		answer: '1020',
		hint: '340 x 3',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 40,
		title: '서재의 사다리',
		question: '[서재의 기록]\n책장 사다리에는 15cm 간격의 눈금이 20개 새겨져 있다.\n첫 눈금부터 마지막 눈금까지의 길이는 몇 cm인가? (숫자만 입력)',
		answer: '285',
		hint: '눈금 20개 사이의 간격은 19개입니다. 15 x 19',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 41,
		title: '거울 알파벳',
		question: '[서재의 기록]\n이 저택의 암호는 알파벳을 거꾸로 짝짓는다: A↔Z, B↔Y, C↔X ... 이런 식으로 각 글자를 정반대 글자로 바꾼다.\n암호문 "NZK"의 원문은? (대문자 3글자)',
		answer: 'MAP',
		hint: 'N은 M과, Z는 A와, K는 P와 서로 짝입니다.',
		type: '암호',
		difficulty: 3,
	},
	{
		id: 42,
		title: '4의 배수 자물쇠',
		question: '[지하실의 기록]\n금고 다이얼은 4로 나누어 떨어지는 수에서만 열린다.\n다음 중 열리는 수는? 30, 36, 42 (숫자만 입력)',
		answer: '36',
		hint: '36 / 4 = 9',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 43,
		title: '뒤섞인 글자 카드',
		question: '[다락방의 기록]\n글자 카드 "A", "T", "S", "R"이 흩어져 있다.\n이 네 글자를 재배열하면 밤하늘에 빛나는 것을 뜻하는 영어 단어가 된다. 그 단어는? (대문자 4글자)',
		answer: 'STAR',
		hint: '밤하늘에 빛나는 것을 뜻하는 단어입니다.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 44,
		title: '문장의 길이 암호',
		question: '[사무실의 기록]\n오래된 쪽지에 영어 문장 "I OWN THE KEYS"가 적혀 있다.\n각 단어의 글자 수를 순서대로 이어 붙이면 몇 자리 숫자가 되는가? (숫자만 입력)',
		answer: '1334',
		hint: 'I=1글자, OWN=3글자, THE=3글자, KEYS=4글자입니다.',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 45,
		title: '나침반 자물쇠',
		question: '[탑의 기록]\n금고에 나침반 각도표가 붙어 있다: 북=0, 동=90, 남=180, 서=270.\n나침반 바늘이 차례로 동, 남, 서를 가리켰다면, 이 세 각도를 모두 더한 값은? (숫자만 입력)',
		answer: '540',
		hint: '90 + 180 + 270',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 46,
		title: '화단 속 꽃 순서',
		question: '[정원의 기록]\n화분 4개(장미, 튤립, 국화, 백합)가 1~4번 자리에 일렬로 놓여 있다.\n① 백합은 1번 자리에 있다.\n② 국화는 2번 자리에 있지 않다.\n③ 튤립은 국화 바로 오른쪽 자리에 있다.\n④ 장미는 4번(맨 끝) 자리에 있지 않다.\n국화는 몇 번 자리에 있는가? (숫자만 입력)',
		answer: '3',
		hint: '남은 2, 3, 4번 자리 중 국화가 2번이 아니고 튤립이 국화 바로 오른쪽이어야 합니다.',
		type: '추리',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 47,
		title: '세 대의 마차',
		question: '[현관의 기록]\n마차 세 대(빨강, 파랑, 검정)가 차례로 도착했다.\n① 빨간 마차는 파란 마차보다 먼저 도착했다.\n② 검은 마차는 파란 마차보다 늦게 도착했다.\n가장 나중에 도착한 마차는 무슨 색인가? (빨강/파랑/검정 중 입력)',
		answer: '검정',
		hint: '빨강 → 파랑 → 검정 순서로 도착했습니다.',
		type: '추리',
		difficulty: 1,
	},
	{
		id: 48,
		title: '네 자매의 나이',
		question: '[응접실의 기록]\n초상화 속 네 자매의 나이 합은 42살이다.\n① 두리와 세리는 쌍둥이로 각각 10살이다.\n② 하나는 네리보다 6살 많다.\n하나는 몇 살인가? (숫자만 입력)',
		answer: '14',
		hint: '하나와 네리의 나이 합은 42-10-10=22입니다. 네리를 x라 하면 (x+6)+x=22.',
		type: '추리',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 49,
		title: '창고 선반의 도구',
		question: '[정원의 기록]\n도구 4개(삽, 갈퀴, 가위, 호미)가 1~4번 선반(1번이 가장 낮음)에 하나씩 놓여 있다.\n① 가위는 1번 선반에 있다.\n② 갈퀴는 호미보다 낮은 선반에 있다.\n③ 호미는 삽보다 낮은 선반에 있다.\n갈퀴는 몇 번 선반에 있는가? (숫자만 입력)',
		answer: '2',
		hint: '가위=1번을 뺀 나머지 2, 3, 4번에서 갈퀴 < 호미 < 삽 순서가 됩니다.',
		type: '추리',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 50,
		title: '손님 응대',
		question: '[현관의 기록]\n집사가 손님을 맞이하는 과정 조각들을 순서대로 탭하시오.',
		answer: '초인종울림문열기인사하기응접실로안내',
		hint: '소리가 울리고, 문을 열고, 인사한 뒤 안내합니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['초인종울림', '문열기', '인사하기', '응접실로안내'],
	},
	{
		id: 51,
		title: '답장 쓰기',
		question: '[서재의 기록]\n편지에 답장을 쓰는 과정 조각들을 순서대로 탭하시오.',
		answer: '편지받기읽기답장쓰기보내기',
		hint: '받고, 읽고, 쓰고, 보내는 순서입니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['편지받기', '읽기', '답장쓰기', '보내기'],
	},
	{
		id: 52,
		title: '초상화 그리기',
		question: '[다락방의 기록]\n화가가 초상화를 완성하는 과정 조각들을 순서대로 탭하시오.',
		answer: '스케치하기밑색칠하기세부묘사광택내기',
		hint: '밑그림부터 마무리 광택까지의 순서를 떠올려보세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['스케치하기', '밑색칠하기', '세부묘사', '광택내기'],
	},
	{
		id: 53,
		title: '계약서 작성',
		question: '[사무실의 기록]\n오래된 계약서가 작성된 과정 조각들을 순서대로 탭하시오.',
		answer: '초안작성검토하기서명하기봉인하기',
		hint: '작성하고, 검토하고, 서명한 뒤 봉인합니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['초안작성', '검토하기', '서명하기', '봉인하기'],
	},
	{
		id: 54,
		title: '정원 손질',
		question: '[정원의 기록]\n정원사가 정원을 손질하는 과정 조각들을 순서대로 탭하시오.',
		answer: '잡초뽑기물주기가지치기낙엽쓸기',
		hint: '뽑고, 주고, 치고, 쓰는 순서를 떠올려보세요.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['잡초뽑기', '물주기', '가지치기', '낙엽쓸기'],
	},
	{
		id: 55,
		title: '해시계의 침묵',
		question: '[정원의 기록]\n정원의 해시계는 흐린 날에는 아무도 시간을 묻지 않는다.\n그 이유는 무엇일까? (해시계는그림자로시간을알려주기때문에/사람들이바빠서/시계가고장나서 중 입력)',
		answer: '해시계는그림자로시간을알려주기때문에',
		hint: '해시계가 시간을 알려주는 방법을 떠올려보세요.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 56,
		title: '삐걱이지 않는 계단',
		question: '[계단의 기록]\n저택의 모든 계단은 밟으면 삐걱거리는데, 유독 13번째 계단만 소리가 나지 않는다.\n하인들은 이 계단만은 절대 밟지 않는다. 왜일까? (불길해서/함정이라서/다른나무라서 중 입력)',
		answer: '함정이라서',
		hint: '소리가 나지 않는 계단은 다른 계단과 뭔가 다릅니다.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 57,
		title: '그려진 창문의 바람',
		question: '[지하실의 기록]\n지하실 벽에는 창문이 그림으로 그려져 있을 뿐 실제로는 뚫려 있지 않다.\n그런데 그 그림 앞에 서면 희미하게 바람이 느껴진다. 왜일까? (그림뒤에통풍구가있어서/상상이라서/물감냄새때문에 중 입력)',
		answer: '그림뒤에통풍구가있어서',
		hint: '그림이 가리고 있는 벽 뒤쪽을 생각해보세요.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 58,
		title: '탑의 팔각창',
		question: '[탑의 기록]\n탑의 창문은 정팔각형 모양이다.\n이 창틀의 내각 하나의 크기는? (숫자만 입력, 도 단위)',
		answer: '135',
		hint: '(8-2) x 180 / 8',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 59,
		title: '사다리꼴 화단',
		question: '[정원의 기록]\n사다리꼴 모양 화단의 윗변은 6m, 아랫변은 10m, 높이는 4m다.\n이 화단의 넓이는? (숫자만 입력)',
		answer: '32',
		hint: '(윗변 + 아랫변) x 높이 / 2',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 60,
		title: '지도 위 두 지점',
		question: '[서재의 기록]\n저택 지도에서 우물의 위치는 (2, 3), 창고의 위치는 (2, 9)로 표시되어 있다(같은 세로선 위에 있다).\n두 지점 사이의 거리는? (숫자만 입력)',
		answer: '6',
		hint: 'x좌표가 같으므로 y좌표의 차이만 구하면 됩니다.',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},

	// ==========================================
	// Level 3 (30대 / 중학교 2학년 수준) — 방 61~90
	// Rewritten on 2026-08-26 alongside Level 1~2. The original had zero 넌센스
	// rooms and repeated the "N suspects, exactly one lies" liar template four
	// times (id 65/73/81/90) — replaced with constraint-satisfaction reasoning
	// (arrival order, wall placement, weekday, score) and 3 fresh 넌센스 rooms.
	// ==========================================
	{
		id: 61,
		title: '두 골동품 시계',
		question: '[사무실의 기록]\n골동품 시계 두 개의 가격 합은 15만원이고, 비싼 시계가 싼 시계보다 3만원 더 비싸다.\n비싼 시계의 가격은? (숫자만 입력, 만원 단위)',
		answer: '9',
		hint: 'x + y = 15, x - y = 3. 두 식을 더하면 2x = 18',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 62,
		title: '하트 카드 확률',
		question: '[응접실의 기록]\n카드 52장 중 하트는 13장이다. 무작위로 한 장을 뽑을 때 하트가 나올 확률을 기약분수로 나타내면\n분모는 얼마인가? (숫자만 입력)',
		answer: '4',
		hint: '13/52을 약분하면 1/4이 됩니다.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 63,
		title: '삼 년의 이자',
		question: '[사무실의 기록]\n원금 20만원에 연 4% 단리 이자를 3년간 받으면 이자 총액은? (숫자만 입력, 원 단위)',
		answer: '24000',
		hint: '200000 x 0.04 x 3',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 64,
		title: '정원사의 자전거',
		question: '[정원의 기록]\n정원사가 자전거로 54km를 6시간 동안 달렸다.\n시속은 몇 km인가? (숫자만 입력)',
		answer: '9',
		hint: '54 / 6',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 65,
		title: '골동품 촛대 할인',
		question: '[사무실의 기록]\n골동품 촛대 가격 120000원에서 30% 할인하면 얼마인가? (숫자만 입력)',
		answer: '84000',
		hint: '120000 x 0.7',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 66,
		title: '방문객 명부의 빈칸',
		question: '[사무실의 기록]\n방문객 명부에 적힌 나이 8개의 평균은 24살이다.\n일곱 명의 나이 합이 161살일 때, 나머지 한 명의 나이는? (숫자만 입력)',
		answer: '31',
		hint: '평균 24 x 8명 = 192. 192에서 161을 빼세요.',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 67,
		title: '그림자 자로 재는 탑',
		question: '[탑의 기록]\n탑의 그림자 길이는 24m이고, 그림자와 실제 높이의 비율은 4:3(그림자:높이)이다.\n탑의 높이는? (숫자만 입력)',
		answer: '18',
		hint: '24를 4로 나눈 뒤 3을 곱하세요.',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 68,
		title: '두 배로 불어나는 곰팡이',
		question: '[지하실의 기록]\n벽에 핀 곰팡이 자국이 3, 6, 12, 24, 48, ?로 매일 두 배씩 번지고 있다.\n다음 날의 크기는? (숫자만 입력)',
		answer: '96',
		hint: '48 x 2',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 69,
		title: '공배수 찾기',
		question: '[다락방의 기록]\n1부터 30까지의 수 중에서 4와 6의 공배수는 몇 개인가? (숫자만 입력)',
		answer: '2',
		hint: '4와 6의 최소공배수는 12입니다. 12의 배수를 30까지 세어보세요.',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 70,
		title: '제곱수의 계단',
		question: '[다락방의 기록]\n계단 타일에 새겨진 수열: 1, 4, 9, 16, 25, ?\n다음 수는 무엇인가? (숫자만 입력)',
		answer: '36',
		hint: '1², 2², 3², 4², 5², 6²',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 71,
		title: '오각별 자물쇠',
		question: '[지하실의 기록]\n5진수로 표시된 자물쇠 번호 132를 10진수로 바꾸면? (숫자만 입력)',
		answer: '42',
		hint: '1 x 25 + 3 x 5 + 2',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 72,
		title: '아홉수 자물쇠',
		question: '[지하실의 기록]\n자물쇠 규칙: N을 9로 나눈 나머지. 47의 나머지는? (숫자만 입력)',
		answer: '2',
		hint: '47 = 45 + 2, 45는 9의 배수입니다.',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 73,
		title: '제곱 암호판',
		question: '[서재의 기록]\n암호 규칙: 알파벳 순서의 제곱값을 취한다.\nE(5번째 글자)는 어떤 수로 바뀌는가? (숫자만 입력)',
		answer: '25',
		hint: '5 x 5',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 74,
		title: '소수 자물쇠',
		question: '[지하실의 기록]\n금고 다이얼은 소수(1과 자기 자신으로만 나누어지는 수)에서만 열린다.\n다음 중 열리는 수는? 21, 29, 33 (숫자만 입력)',
		answer: '29',
		hint: '21=3x7, 33=3x11이지만 29는 다른 수로 나누어지지 않습니다.',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 75,
		title: '회문수 자물쇠',
		question: '[지하실의 기록]\n이 자물쇠는 앞으로 읽으나 뒤로 읽으나 같은 4자리 수(회문수)에서만 열린다.\n다음 중 열리는 수는? 1234, 3773, 4521 (숫자만 입력)',
		answer: '3773',
		hint: '3773을 거꾸로 읽어도 3773입니다.',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 76,
		title: '다섯 손님의 도착 순서',
		question: '[현관의 기록]\n손님 다섯 명(가, 나, 다, 라, 마)이 차례로 저택에 도착했다.\n① 가는 나보다 늦게 도착했다.\n② 다는 가장 먼저 도착했다.\n③ 라는 나보다 먼저, 마보다 늦게 도착했다.\n④ 마는 가보다 먼저 도착했다.\n두 번째로 도착한 사람은? (가/나/다/라/마 중 입력)',
		answer: '마',
		hint: '순서를 정리하면 다음으로 마, 라, 나, 가 순서가 이어집니다.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 77,
		title: '액자 다섯 개의 벽',
		question: '[응접실의 기록]\n액자 다섯 개(풍경화, 인물화, 정물화, 추상화, 판화)가 벽의 1~5번 자리에 하나씩 걸려 있다.\n① 풍경화는 3번 자리에 있다.\n② 인물화는 풍경화 바로 옆(2번 또는 4번) 자리에 있다.\n③ 정물화는 1번 자리에 있지 않다.\n④ 추상화는 5번 자리에 있다.\n⑤ 판화는 정물화보다 작은 번호 자리에 있다.\n판화는 몇 번 자리에 있는가? (숫자만 입력)',
		answer: '1',
		hint: '추상화=5, 풍경화=3을 제외한 1, 2, 4번 중 정물화가 1번이 아니고 판화가 정물화보다 작은 번호여야 합니다.',
		type: '추리',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 78,
		title: '방문 요일 추리',
		question: '[응접실의 기록]\n방문객 네 명(민수, 지은, 현우, 수진)이 서로 다른 요일(월, 화, 수, 목)에 저택을 찾았다.\n① 지은은 민수보다 하루 먼저 왔다.\n② 현우는 목요일에 왔다.\n③ 수진은 월요일에 왔다.\n민수는 무슨 요일에 왔는가? (월요일/화요일/수요일/목요일 중 입력)',
		answer: '수요일',
		hint: '월요일과 목요일은 이미 정해졌으므로, 남은 화요일과 수요일 중 지은이 민수보다 하루 먼저입니다.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 79,
		title: '카드놀이 점수',
		question: '[응접실의 기록]\n네 사람이 카드놀이를 했다. 전체 점수 합은 100점이다.\n① 정우는 혜진보다 20점 많다.\n② 태호와 수빈은 점수가 같고 각각 15점이다.\n③ 정우와 혜진의 점수 합은 70점이다.\n정우의 점수는? (숫자만 입력)',
		answer: '45',
		hint: '혜진을 x라 하면 정우는 x+20이고, x + (x+20) = 70입니다.',
		type: '추리',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 80,
		title: '만찬 코스',
		question: '[식당의 기록]\n정찬 코스 요리 조각들을 순서대로 탭하시오.',
		answer: '에피타이저수프메인요리디저트',
		hint: '가벼운 것부터 무거운 것, 마지막은 달콤한 것입니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['에피타이저', '수프', '메인요리', '디저트'],
	},
	{
		id: 81,
		title: '숨은 글씨 해독',
		question: '[서재의 기록]\n촛불로만 보이는 비밀 편지를 해독하는 과정 조각들을 순서대로 탭하시오.',
		answer: '봉투확인촛불로비추기숨은글씨읽기암호풀기',
		hint: '확인하고, 비추고, 읽고, 마지막에 풉니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['봉투확인', '촛불로비추기', '숨은글씨읽기', '암호풀기'],
	},
	{
		id: 82,
		title: '무도회 준비',
		question: '[응접실의 기록]\n저택 무도회를 준비하는 과정 조각들을 순서대로 탭하시오.',
		answer: '초대장보내기드레스코드정하기음악준비손님맞이',
		hint: '초대하고, 정하고, 준비한 뒤 맞이합니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['초대장보내기', '드레스코드정하기', '음악준비', '손님맞이'],
	},
	{
		id: 83,
		title: '유언장 공개',
		question: '[서재의 기록]\n오래된 유언장을 공개하는 과정 조각들을 순서대로 탭하시오.',
		answer: '봉인확인증인모으기유언장읽기서명확인',
		hint: '봉인을 확인하고, 증인을 모으고, 읽은 뒤 서명을 확인합니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['봉인확인', '증인모으기', '유언장읽기', '서명확인'],
	},
	{
		id: 84,
		title: '마차 도착 시각표',
		question: '[현관의 기록]\n마차 도착 시각 조각들을 이른 시각부터 순서대로 탭하시오.',
		answer: '오전9시오전11시오후1시오후3시',
		hint: '오전 먼저, 그 다음 오후 순서입니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['오전9시', '오전11시', '오후1시', '오후3시'],
	},
	{
		id: 85,
		title: '멈춘 시계',
		question: '[지하실의 기록]\n지하실의 낡은 시계는 완전히 멈춰 있다. 그런데도 하루에 두 번은 정확한 시각을 가리킨다.\n왜일까? (배터리가없어서/멈춘시각과같은시각이하루에두번있어서/고장나서 중 입력)',
		answer: '멈춘시각과같은시각이하루에두번있어서',
		hint: '하루 24시간 동안 같은 시각이 몇 번 돌아오는지 생각해보세요.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 86,
		title: '죽은 나뭇가지',
		question: '[정원의 기록]\n정원사는 매년 봄, 죽은 나뭇가지 일부를 일부러 치우지 않고 남겨둔다.\n왜일까? (게을러서/새둥지를위해/보기좋아서 중 입력)',
		answer: '새둥지를위해',
		hint: '작은 새들이 그 가지에 무엇을 짓는지 생각해보세요.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 87,
		title: '지도에 없는 방',
		question: '[다락방의 기록]\n저택의 공식 지도에는 그려져 있지 않은 방이 하나 있다. 그런데 실제로 가보면 그 방이 있다.\n왜일까? (지도제작자의실수/일부러숨긴비밀방이라서/유령의방이라서 중 입력)',
		answer: '일부러숨긴비밀방이라서',
		hint: '지도에 없는 방을 굳이 만든 사람의 의도를 생각해보세요.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 88,
		title: '피타고라스의 정원',
		question: '[정원의 기록]\n직각삼각형 모양 정원의 두 변이 6m, 8m일 때 빗변의 길이는? (숫자만 입력)',
		answer: '10',
		hint: '6²+8²의 제곱근을 구하세요 (6-8-10 직각삼각형).',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 89,
		title: '부채꼴 창문',
		question: '[탑의 기록]\n탑의 부채꼴 창문은 원의 3/8에 해당한다.\n이 부채꼴의 중심각은? (숫자만 입력, 도 단위)',
		answer: '135',
		hint: '360 x 3/8',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 90,
		title: '원기둥 촛대의 지름',
		question: '[보관실의 기록]\n원기둥 모양 촛대의 둘레(원주)는 약 44cm이고, 원주율은 22/7로 계산한다.\n촛대의 지름은 몇 cm인가? (숫자만 입력)',
		answer: '14',
		hint: '지름 = 원주 / 원주율 = 44 / (22/7)',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	// ==========================================
	// Level 4 (40대 이상 / 중학교 3학년 수준) — 방 91~120
	// ==========================================
	{
		id: 91,
		title: '인수분해 자물쇠',
		question: '[지하실의 기록]\nx² - 5x + 6 = 0의 두 해 중 더 큰 값은? (숫자만 입력)',
		answer: '3',
		hint: '(x-2)(x-3) = 0',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 92,
		title: '피타고라스 응용',
		question: '[정원의 기록]\n직각삼각형의 빗변이 13, 한 변이 5일 때 나머지 한 변은? (숫자만 입력)',
		answer: '12',
		hint: '5-12-13 비율입니다.',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 93,
		title: '모듈러 응용',
		question: '[지하실의 기록]\n규칙: (3N+1)을 5로 나눈 나머지. N=7일 때 값은? (숫자만 입력)',
		answer: '2',
		hint: '3 x 7 + 1 = 22, 22를 5로 나눈 나머지',
		type: '암호',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 94,
		title: '삼차 수열',
		question: '[다락방의 기록]\n1, 8, 27, 64, ?\n다음 수는? (숫자만 입력)',
		answer: '125',
		hint: '5의 세제곱입니다.',
		type: '관찰',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 95,
		title: '암호 알고리즘 조각',
		question: '[서재의 기록]\n암호 절차 조각 "암호화", "평문", "전송", "복호화"를\n올바른 처리 순서로 탭하시오.',
		answer: '평문암호화전송복호화',
		hint: '메시지가 만들어지고 전달되는 순서를 생각해보세요.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['평문', '암호화', '전송', '복호화'],
	},
	{
		id: 96,
		title: '거울 속 초상화',
		question: '[응접실의 기록]\n초상화 속 인물은 거울을 보고 있지만 자신의 얼굴이 보이지 않는다고 한다.\n왜일까? (그림이라서/눈을감아서/거울이깨져서 중 입력)',
		answer: '그림이라서',
		hint: '초상화 속 인물은 실제로 보는 행위를 할 수 없습니다.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 97,
		title: '복리 이자',
		question: '[사무실의 기록]\n원금 10만원을 연 10% 복리로 2년간 예치하면 원리금 합계는? (숫자만 입력)',
		answer: '121000',
		hint: '100000 x 1.1 x 1.1',
		type: '연산',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 98,
		title: '삼각형의 닮음',
		question: '[서재의 기록]\n닮음비가 1:3인 두 삼각형에서 작은 삼각형 넓이가 4일 때\n큰 삼각형 넓이는? (숫자만 입력)',
		answer: '36',
		hint: '넓이비는 (1:3)² = 1:9',
		type: '도형',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 99,
		title: '깨지지 않는 접시',
		question: '[부엌의 기록]\n접시를 2층 창문에서 던져도 깨지지 않았다. 왜일까? (1층에서던져서/창문이닫혀있어서/고무접시라서 중 입력)',
		answer: '1층에서던져서',
		hint: '"2층에서 떨어뜨렸다"고 하지 않았습니다. 던진 방향을 다시 생각해보세요.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 100,
		title: '긴 암호 문장',
		question: '[지하실의 기록]\n조각난 문장 "지하실에", "숨겨진", "금고의", "열쇠가", "있다"를\n올바른 문장 순서로 탭하시오.',
		answer: '지하실에숨겨진금고의열쇠가있다',
		hint: '장소-수식어-목적어-서술어 순서를 생각해보세요.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['지하실에', '숨겨진', '금고의', '열쇠가', '있다'],
	},
	{
		id: 101,
		title: '피보나치 저택',
		question: '[다락방의 기록]\n1, 1, 2, 3, 5, 8, ?\n다음 수는? (숫자만 입력)',
		answer: '13',
		hint: '앞의 두 수를 더합니다.',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 102,
		title: '비례식 자물쇠',
		question: '[지하실의 기록]\nx:6 = 10:15 일 때 x의 값은? (숫자만 입력)',
		answer: '4',
		hint: '6 x 10 / 15',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 103,
		title: '다섯 용의자의 함정',
		question: '[응접실의 기록]\n은식기가 사라졌다. 다섯 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "B가 범인이다."\n범인은 누구인가? (A/B/C/D/E 중 입력)',
		answer: 'B',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	{
		id: 104,
		title: '저택의 마지막 진실',
		question: '[응접실의 기록]\n보물이 사라졌다. 여섯 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "C가 범인이다."\n범인은 누구인가? (A~F 중 입력)',
		answer: 'C',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	{
		id: 105,
		title: '제곱근 자물쇠',
		question: '[지하실의 기록]\n169의 제곱근은? (숫자만 입력)',
		answer: '13',
		hint: '13 x 13 = 169',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 106,
		title: '농도 계산',
		question: '[부엌의 기록]\n소금물 200g에 소금이 20g 녹아 있다.\n농도는 몇 %인가? (숫자만 입력)',
		answer: '10',
		hint: '20 / 200 x 100',
		type: '연산',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 107,
		title: '최종 암호 배열',
		question: '[지하실의 기록]\n금고 다이얼 조각 5, 3, 8, 1, 9, 2를\n오름차순으로 탭하여 최종 암호를 만드시오.',
		answer: '123589',
		hint: '작은 수부터 고르세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['1', '2', '3', '5', '8', '9'],
	},
	{
		id: 108,
		title: '없어지지 않는 초',
		question: '[보관실의 기록]\n촛불 10개 중 2개가 바람에 꺼졌다. 잠시 후 다시 세어보니 촛불은 여전히 10개였다.\n어떻게 된 일일까? (다시켰다/꺼진게아니다/촛대를더가져왔다 중 입력)',
		answer: '다시켰다',
		hint: '꺼진 초를 그대로 둘 필요는 없습니다.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 109,
		title: '등비수열의 저택',
		question: '[다락방의 기록]\n2, 6, 18, 54, ?\n다음 수는? (숫자만 입력)',
		answer: '162',
		hint: '3배씩 증가합니다.',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 110,
		title: '복합 모듈러',
		question: '[지하실의 기록]\n규칙: N을 4로 나눈 나머지에 3을 곱한다. N=15일 때 값은? (숫자만 입력)',
		answer: '9',
		hint: '15를 4로 나눈 나머지는 3, 3 x 3 = 9',
		type: '암호',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 111,
		title: '최종 방정식 2',
		question: '[사무실의 기록]\n2(x+3) = 16.\nx의 값은? (숫자만 입력)',
		answer: '5',
		hint: 'x + 3 = 8',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 112,
		title: '일곱 용의자의 함정',
		question: '[응접실의 기록]\n마지막 보석이 사라졌다. 일곱 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "나는 범인이 아니다."\nG: "D가 범인이다."\n범인은 누구인가? (A~G 중 입력)',
		answer: 'D',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 5,
	},
	{
		id: 113,
		title: '닮음 그림자',
		question: '[정원의 기록]\n실제 높이 6m인 조각상의 그림자가 4m이다.\n같은 시각 그림자 길이가 10m인 나무의 실제 높이는? (숫자만 입력)',
		answer: '15',
		hint: '6:4 = x:10',
		type: '도형',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 114,
		title: '먼지 쌓인 시계',
		question: '[다락방의 기록]\n멈춘 지 오래된 시계가 있다. 하루에 시간이 정확히 두 번 맞는 시계는\n항상 움직이는 시계와 멈춘 시계 중 어느 쪽일까? (멈춘시계/움직이는시계 중 입력)',
		answer: '멈춘시계',
		hint: '조금씩 어긋나는 시계는 하루에 정확한 시각을 지나칠 뿐 정확히 멈추지 않습니다.',
		type: '넌센스',
		difficulty: 3,
	},
	{
		id: 115,
		title: '확률의 방',
		question: '[응접실의 기록]\n주머니에 빨간 공 3개, 파란 공 2개가 있다.\n빨간 공을 뽑을 확률을 기약분수로 나타낼 때 분모는? (숫자만 입력)',
		answer: '5',
		hint: '3/5',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 116,
		title: '최종 문서 조각',
		question: '[서재의 기록]\n마지막 문서 조각 "저택의", "모든", "비밀이", "풀렸다"를\n올바른 문장 순서로 탭하시오.',
		answer: '저택의모든비밀이풀렸다',
		hint: '주어부터 순서대로 읽어보세요.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['저택의', '모든', '비밀이', '풀렸다'],
	},
	{
		id: 117,
		title: '두 개의 열쇠',
		question: '[현관의 기록]\n집사가 열쇠 두 개를 건넸다. 하나는 진짜, 하나는 가짜다.\n"가짜 열쇠는 항상 거짓말을 한다"는 쪽지가 있다. 열쇠가 말을 할 리 없는데도\n이 쪽지가 힌트가 되는 이유는 무엇일까? (쪽지자체가단서라서/열쇠가말한다/장난이다 중 입력)',
		answer: '쪽지자체가단서라서',
		hint: '열쇠가 말하는 게 아니라, 쪽지의 내용 자체가 논리 퍼즐의 설정입니다.',
		type: '넌센스',
		difficulty: 3,
	},
	{
		id: 118,
		title: '최종 규칙 찾기',
		question: '[다락방의 기록]\n2, 5, 11, 23, 47, ?\n다음 수는? (숫자만 입력)',
		answer: '95',
		hint: '각 항에 2를 곱하고 1을 더합니다.',
		type: '관찰',
		difficulty: 5,
		inputType: 'number',
	},
	{
		id: 119,
		title: '최종 모듈러 자물쇠',
		question: '[지하실의 기록]\n규칙: N²을 7로 나눈 나머지. N=10일 때 값은? (숫자만 입력)',
		answer: '2',
		hint: '10² = 100, 100을 7로 나눈 나머지',
		type: '암호',
		difficulty: 5,
		inputType: 'number',
	},
	{
		id: 120,
		title: '저택 최후의 진실',
		question: '[응접실의 기록]\n저택 탈출의 마지막 관문. 여덟 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "나는 범인이 아니다."\nG: "나는 범인이 아니다."\nH: "E가 범인이다."\n범인은 누구인가? (A~H 중 입력)',
		answer: 'E',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 5,
	},
];
