import 'server-only';
import { Room } from '@/types/room';

export const rooms: Room[] = [
	// ==========================================
	// Level 1 (10대 / 초등 고학년 수준) — 방 1~30
	// ==========================================
	{
		id: 1,
		title: '낡은 계산기',
		question: '[저택의 기록]\n지하실에서 낡은 계산기를 발견했다.\n24 + 19 = ? (숫자만 입력)',
		answer: '43',
		hint: '24+19를 계산하세요.',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 2,
		title: '촛불의 수',
		question: '[저택의 기록]\n촛대마다 촛불이 4개씩 꽂혀 있고, 촛대는 5개 있다.\n촛불은 모두 몇 개인가? (숫자만 입력)',
		answer: '20',
		hint: '4 x 5를 계산하세요.',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 3,
		title: '그림자 놀이',
		question: '[정원의 기록]\n정원 조각상의 그림자 길이는 해가 질수록 2배씩 길어진다.\n처음 그림자 길이가 3m였다면, 두 번 길어진 뒤 그림자 길이는? (숫자만 입력, m 제외)',
		answer: '12',
		hint: '3 -> 6 -> 12',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 4,
		title: '알파벳 자리',
		question: '[서재의 기록]\n서재 책장에 A=1, B=2, C=3 규칙이 붙어 있다.\nE는 몇 번째 글자인가? (숫자만 입력)',
		answer: '5',
		hint: 'A부터 순서대로 세어보세요.',
		type: '암호',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 5,
		title: '이름표 조각',
		question: '[응접실의 기록]\n바닥에 떨어진 글자 조각 4개를 주웠다.\n올바른 순서로 탭하면 저택에서 가장 중요한 장소 이름이 된다.',
		answer: 'HOME',
		hint: '영어로 "집"을 뜻하는 4글자 단어입니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['H', 'O', 'M', 'E'],
	},
	{
		id: 6,
		title: '세 명의 하인',
		question: '[응접실의 기록]\n하인 세 명 중 한 명이 촛대를 깨뜨렸다.\nA: "나는 안 그랬어요."\nB: "C가 그랬어요."\nC: "B가 거짓말을 하고 있어요."\n이 중 단 한 명만 진실을 말한다면, 촛대를 깨뜨린 사람은 누구인가? (대문자 1글자)',
		answer: 'A',
		hint: '각 사람이 진실을 말한다고 하나씩 가정해보고, 모순이 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 7,
		title: '정원의 장미',
		question: '[정원의 기록]\n장미가 6송이씩 심긴 화단이 5개 있다.\n장미는 모두 몇 송이인가? (숫자만 입력)',
		answer: '30',
		hint: '6 x 5를 계산하세요.',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 8,
		title: '액자의 둘레',
		question: '[서재의 기록]\n가로 6, 세로 3인 직사각형 액자의 둘레는? (숫자만 입력)',
		answer: '18',
		hint: '둘레 = 2 x (가로 + 세로)',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 9,
		title: '문이 아닌 문',
		question: '[복도의 기록]\n저택에는 열리지 않는 문이 하나 있다. 사실 그 문은 벽에 그려진 그림이다.\n이 문을 열려면 무엇을 해야 할까? (그림이다/열지않는다/부순다 중 입력)',
		answer: '열지않는다',
		hint: '그림은 문이 아닙니다.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 10,
		title: '모스 촛불',
		question: '[탑의 기록]\n촛불 신호가 짧게 셋, 길게 셋, 짧게 셋으로 반복된다.\n세계 공통 구조 신호 세 글자는 무엇인가? (대문자 3글자)',
		answer: 'SOS',
		hint: '가장 유명한 조난 신호입니다.',
		type: '암호',
		difficulty: 1,
	},
	{
		id: 11,
		title: '사건의 순서',
		question: '[복도의 기록]\n집사가 목격한 사건 조각: 비명, 발소리, 정적.\n실제 벌어진 순서대로 탭하시오.',
		answer: '발소리비명정적',
		hint: '발소리가 들리고, 비명이 들리고, 그다음 조용해졌습니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['발소리', '비명', '정적'],
	},
	{
		id: 12,
		title: '은촛대 무게',
		question: '[보관실의 기록]\n은촛대 하나의 무게는 250g이다.\n촛대 4개의 무게 합은? (숫자만 입력)',
		answer: '1000',
		hint: '250 x 4',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 13,
		title: '시계의 각도',
		question: '[탑의 기록]\n저택 시계가 3시 정각을 가리킨다.\n시침과 분침이 이루는 각도는? (숫자만 입력)',
		answer: '90',
		hint: '3시는 직각을 이룹니다.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 14,
		title: '책장의 순서',
		question: '[서재의 기록]\n책장에 A, C, E, G 순서로 책이 꽂혀 있다.\n다음에 올 알파벳은? (대문자 1글자)',
		answer: 'I',
		hint: '한 칸씩 건너뜁니다.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 15,
		title: '정원사의 알리바이',
		question: '[정원의 기록]\n정원사, 요리사, 마부 중 한 명이 온실 유리를 깼다.\n정원사: "나는 그 시간 온실에 없었다."\n요리사: "정원사는 사실을 말하고 있다."\n마부: "나는 범인이 아니다."\n이 중 딱 한 명만 거짓말을 하고 있고, 거짓말한 사람이 범인이다. 범인은 누구인가? (정원사/요리사/마부 중 입력)',
		answer: '마부',
		hint: '각자 거짓말한다고 가정했을 때 모순이 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 16,
		title: '복도의 촛불 간격',
		question: '[복도의 기록]\n복도에 촛불이 3m 간격으로 놓여 있다. 촛불이 5개라면\n첫 촛불부터 마지막 촛불까지 거리는? (숫자만 입력)',
		answer: '12',
		hint: '간격 수는 촛불 수보다 1개 적습니다. 4간격 x 3m',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 17,
		title: '정원의 화단',
		question: '[정원의 기록]\n한 변이 5m인 정사각형 화단의 넓이는? (숫자만 입력)',
		answer: '25',
		hint: '5 x 5',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 18,
		title: '빈 방',
		question: '[다락방의 기록]\n저택에서 가장 물건이 많은 방은 사실 텅 빈 방이다.\n이 방에 가득한 것은 무엇일까? (공기/먼지/어둠 중 입력)',
		answer: '공기',
		hint: '눈에 보이지 않아도 방을 채우고 있는 것입니다.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 19,
		title: '편지 조각',
		question: '[서재의 기록]\n찢어진 편지 조각에 적힌 글자들.\n순서대로 탭하면 저택의 비밀을 뜻하는 단어가 된다.',
		answer: 'SECRET',
		hint: '영어로 "비밀"을 뜻하는 6글자 단어입니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['S', 'E', 'C', 'R', 'E', 'T'],
	},
	{
		id: 20,
		title: '하인들의 새참',
		question: '[부엌의 기록]\n빵 3개씩 담긴 바구니가 4개 있다.\n빵은 모두 몇 개인가? (숫자만 입력)',
		answer: '12',
		hint: '3 x 4',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 21,
		title: '역순 이름',
		question: '[현관의 기록]\n오래된 문패에 "ESUOH"라고 적혀 있다.\n뒤집어 읽으면 어떤 단어가 되는가? (대문자 5글자)',
		answer: 'HOUSE',
		hint: '글자를 거꾸로 읽어보세요.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 22,
		title: '촛대 무늬',
		question: '[보관실의 기록]\n촛대 3개에는 별 무늬가, 2개에는 달 무늬가 새겨져 있다.\n촛대는 모두 몇 개인가? (숫자만 입력)',
		answer: '5',
		hint: '3 + 2',
		type: '관찰',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 23,
		title: '삼각 지붕',
		question: '[탑의 기록]\n삼각형 모양 지붕 창문의 세 각의 합은 몇 도인가? (숫자만 입력)',
		answer: '180',
		hint: '삼각형 내각의 합입니다.',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 24,
		title: '숫자 계단',
		question: '[계단의 기록]\n계단에 적힌 숫자 조각들을 작은 수부터 순서대로 탭하시오.',
		answer: '12345',
		hint: '가장 작은 수부터 차례로 고르세요.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['1', '2', '3', '4', '5'],
	},
	{
		id: 25,
		title: '다락방의 열쇠',
		question: '[다락방의 기록]\n다락방 열쇠를 잃어버렸다. 하녀, 집사, 정원사 중 한 명이 가지고 있다.\n하녀: "내가 가지고 있어요."\n집사: "하녀는 거짓말을 하고 있어요."\n정원사: "나는 가지고 있지 않아요."\n이 중 딱 한 명만 진실을 말한다면, 열쇠를 가진 사람은 누구인가? (하녀/집사/정원사 중 입력)',
		answer: '정원사',
		hint: '각자 진실을 말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 26,
		title: '초의 개수',
		question: '[보관실의 기록]\n촛대에 초가 7개씩 3줄로 꽂혀 있다.\n초는 모두 몇 개인가? (숫자만 입력)',
		answer: '21',
		hint: '7 x 3',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 27,
		title: '그림 속 숫자',
		question: '[다락방의 기록]\n벽화에 적힌 숫자 나열: 2, 4, 6, 8, ?\n다음 숫자는? (숫자만 입력)',
		answer: '10',
		hint: '짝수가 2씩 증가합니다.',
		type: '관찰',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 28,
		title: '자리 바꾸기',
		question: '[서재의 기록]\n암호 규칙: 각 알파벳을 바로 다음 알파벳으로 바꾼다.\n"HOUSE"를 이 규칙으로 암호화하면? (대문자 5글자)',
		answer: 'IPVTF',
		hint: 'H->I, O->P, U->V, S->T, E->F',
		type: '암호',
		difficulty: 3,
	},
	{
		id: 29,
		title: '정원의 오각형 분수',
		question: '[정원의 기록]\n오각형 모양 분수의 변은 몇 개인가? (숫자만 입력)',
		answer: '5',
		hint: '오각형입니다.',
		type: '도형',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 30,
		title: '최종 문장',
		question: '[응접실의 기록]\n응접실 바닥에 흩어진 문장 조각들을 순서대로 탭하시오.',
		answer: '저택에서탈출성공했다',
		hint: '주어-목적어-서술어 순서를 생각해보세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['저택에서', '탈출', '성공했다'],
	},
];
