import 'server-only';
import { Room } from '@/types/room';

// Type mix guideline (see docs/superpowers/specs/2026-07-04-level-system-and-puzzle-content-design.md):
// 추리 and 넌센스 land slightly under their per-category guideline range across the
// full 120-room set (14 and 9 respectively) — accepted intentionally, since padding
// 추리 further would only repeat the existing "N people, one accuses" template rather
// than add real variety.
export const rooms: Room[] = [
	// ==========================================
	// Level 1 (10대 / 초등 고학년 수준) — 방 1~30
	// ==========================================
	{
		id: 1,
		title: '숫자 규칙 추리',
		question: '[저택의 기록]\n지하실 계산기 화면에 숫자가 깜빡인다.\n3, 6, 11, 18, ?\n다음 숫자는 무엇인가? (숫자만 입력)',
		answer: '29',
		hint: '숫자 사이의 차이를 확인해보세요.',
		type: '규칙추리',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 2,
		title: '촛불의 흔적',
		question: '[저택의 기록]\n촛대마다 촛불이 4개씩 꽂혀 있고, 촛대는 5개 있다.\n그중 3개는 완전히 꺼졌고, 하인이 새 촛불 2개를 더 꽂았다.\n지금 불을 밝힐 수 있는 촛불은 모두 몇 개인가? (숫자만 입력)',
		answer: '19',
		hint: '처음 촛불 수를 구한 뒤, 꺼진 촛불을 빼고 새 촛불을 더하세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 3,
		title: '그림자 놀이',
		question: '[정원의 기록]\n정원 조각상의 그림자는 해가 기울 때마다 2배로 길어진다.\n처음 그림자 길이가 2m였고, 세 번 길어진 뒤 문턱에 닿아 3m가 가려졌다.\n보이는 그림자 길이는 몇 m인가? (숫자만 입력, m 제외)',
		answer: '13',
		hint: '2m를 세 번 2배로 만든 뒤, 가려진 3m를 빼세요.',
		type: '규칙추리',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 4,
		title: '알파벳 합계',
		question: '[서재의 기록]\n서재 책장에 A=1, B=2, C=3 ... Z=26 규칙이 붙어 있다.\n책등에 적힌 암호 CANDLE의 알파벳 값을 모두 더하면 얼마인가? (숫자만 입력)',
		answer: '39',
		hint: 'C=3, A=1처럼 각 글자의 값을 찾은 뒤 모두 더하세요.',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 5,
		title: '이름표 조각',
		question: '[응접실의 기록]\n바닥에 떨어진 글자 조각 4개를 주웠다.\n올바른 순서로 탭하면 저택에서 가장 중요한 장소 이름이 된다.',
		answer: 'HOME',
		hint: '영어로 "집"을 뜻하는 4글자 단어입니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['H', 'O', 'M', 'E'],
	},
	{
		id: 6,
		title: '세 명의 하인',
		question: '[응접실의 기록]\n하인 세 명 중 한 명이 촛대를 깨뜨렸다.\nA: "나는 안 그랬어요."\nB: "C가 그랬어요."\nC: "B가 거짓말을 하고 있어요."\n이 중 단 한 명만 진실을 말한다면, 촛대를 깨뜨린 사람은 누구인가? (대문자 1글자)',
		answer: 'A',
		hint: '각 사람이 진실을 말한다고 하나씩 가정해보고, 모순이 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 7,
		title: '정원의 장미',
		question: '[정원의 기록]\n장미가 6송이씩 심긴 화단이 5개 있다.\n장미는 모두 몇 송이인가? (숫자만 입력)',
		answer: '30',
		hint: '6 x 5를 계산하세요.',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 8,
		title: '액자의 둘레',
		question: '[서재의 기록]\n가로 6, 세로 3인 직사각형 액자의 둘레는? (숫자만 입력)',
		answer: '18',
		hint: '둘레 = 2 x (가로 + 세로)',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 9,
		title: '문이 아닌 문',
		question: '[복도의 기록]\n저택에는 열리지 않는 문이 하나 있다. 사실 그 문은 벽에 그려진 그림이다.\n이 문을 열려면 무엇을 해야 할까? (그림이다/열지않는다/부순다 중 입력)',
		answer: '열지않는다',
		hint: '그림은 문이 아닙니다.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 10,
		title: '모스 촛불',
		question: '[탑의 기록]\n촛불 신호가 짧게 셋, 길게 셋, 짧게 셋으로 반복된다.\n세계 공통 구조 신호 세 글자는 무엇인가? (대문자 3글자)',
		answer: 'SOS',
		hint: '가장 유명한 조난 신호입니다.',
		type: '암호',
		difficulty: 1,
	},
	{
		id: 11,
		title: '사건의 순서',
		question: '[복도의 기록]\n집사가 목격한 사건 조각: 비명, 발소리, 정적.\n실제 벌어진 순서대로 탭하시오.',
		answer: '발소리비명정적',
		hint: '발소리가 들리고, 비명이 들리고, 그다음 조용해졌습니다.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['발소리', '비명', '정적'],
	},
	{
		id: 12,
		title: '은촛대 무게',
		question: '[보관실의 기록]\n은촛대 하나의 무게는 250g이다.\n촛대 4개의 무게 합은? (숫자만 입력)',
		answer: '1000',
		hint: '250 x 4',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 13,
		title: '시계의 각도',
		question: '[탑의 기록]\n저택 시계가 3시 정각을 가리킨다.\n시침과 분침이 이루는 각도는? (숫자만 입력)',
		answer: '90',
		hint: '3시는 직각을 이룹니다.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 14,
		title: '책장의 순서',
		question: '[서재의 기록]\n책장에 A, C, E, G 순서로 책이 꽂혀 있다.\n다음에 올 알파벳은? (대문자 1글자)',
		answer: 'I',
		hint: '한 칸씩 건너뜁니다.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 15,
		title: '정원사의 알리바이',
		question: '[정원의 기록]\n정원사, 요리사, 마부 중 한 명이 온실 유리를 깼다.\n정원사: "나는 그 시간 온실에 없었다."\n요리사: "정원사는 사실을 말하고 있다."\n마부: "나는 범인이 아니다."\n이 중 딱 한 명만 거짓말을 하고 있고, 거짓말한 사람이 범인이다. 범인은 누구인가? (정원사/요리사/마부 중 입력)',
		answer: '마부',
		hint: '각자 거짓말한다고 가정했을 때 모순이 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 16,
		title: '복도의 촛불 간격',
		question: '[복도의 기록]\n복도에 촛불이 3m 간격으로 놓여 있다. 촛불이 5개라면\n첫 촛불부터 마지막 촛불까지 거리는? (숫자만 입력)',
		answer: '12',
		hint: '간격 수는 촛불 수보다 1개 적습니다. 4간격 x 3m',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 17,
		title: '정원의 화단',
		question: '[정원의 기록]\n한 변이 5m인 정사각형 화단의 넓이는? (숫자만 입력)',
		answer: '25',
		hint: '5 x 5',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 18,
		title: '빈 방',
		question: '[다락방의 기록]\n저택에서 가장 물건이 많은 방은 사실 텅 빈 방이다.\n이 방에 가득한 것은 무엇일까? (공기/먼지/어둠 중 입력)',
		answer: '공기',
		hint: '눈에 보이지 않아도 방을 채우고 있는 것입니다.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 19,
		title: '편지 조각',
		question: '[서재의 기록]\n찢어진 편지 조각에 적힌 글자들.\n순서대로 탭하면 저택의 비밀을 뜻하는 단어가 된다.',
		answer: 'SECRET',
		hint: '영어로 "비밀"을 뜻하는 6글자 단어입니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['S', 'E', 'C', 'R', 'E', 'T'],
	},
	{
		id: 20,
		title: '하인들의 새참',
		question: '[부엌의 기록]\n빵 3개씩 담긴 바구니가 4개 있다.\n빵은 모두 몇 개인가? (숫자만 입력)',
		answer: '12',
		hint: '3 x 4',
		type: '연산',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 21,
		title: '역순 이름',
		question: '[현관의 기록]\n오래된 문패에 "ESUOH"라고 적혀 있다.\n뒤집어 읽으면 어떤 단어가 되는가? (대문자 5글자)',
		answer: 'HOUSE',
		hint: '글자를 거꾸로 읽어보세요.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 22,
		title: '촛대 무늬',
		question: '[보관실의 기록]\n촛대 3개에는 별 무늬가, 2개에는 달 무늬가 새겨져 있다.\n촛대는 모두 몇 개인가? (숫자만 입력)',
		answer: '5',
		hint: '3 + 2',
		type: '관찰',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 23,
		title: '삼각 지붕',
		question: '[탑의 기록]\n삼각형 모양 지붕 창문의 세 각의 합은 몇 도인가? (숫자만 입력)',
		answer: '180',
		hint: '삼각형 내각의 합입니다.',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 24,
		title: '숫자 계단',
		question: '[계단의 기록]\n계단에 적힌 숫자 조각들을 작은 수부터 순서대로 탭하시오.',
		answer: '12345',
		hint: '가장 작은 수부터 차례로 고르세요.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['1', '2', '3', '4', '5'],
	},
	{
		id: 25,
		title: '다락방의 열쇠',
		question: '[다락방의 기록]\n다락방 열쇠를 잃어버렸다. 하녀, 집사, 정원사 중 한 명이 가지고 있다.\n하녀: "내가 가지고 있어요."\n집사: "하녀는 거짓말을 하고 있어요."\n정원사: "나는 가지고 있지 않아요."\n이 중 딱 한 명만 진실을 말한다면, 열쇠를 가진 사람은 누구인가? (하녀/집사/정원사 중 입력)',
		answer: '정원사',
		hint: '각자 진실을 말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 26,
		title: '초의 개수',
		question: '[보관실의 기록]\n촛대에 초가 7개씩 3줄로 꽂혀 있다.\n초는 모두 몇 개인가? (숫자만 입력)',
		answer: '21',
		hint: '7 x 3',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 27,
		title: '그림 속 숫자',
		question: '[다락방의 기록]\n벽화에 적힌 숫자 나열: 2, 4, 6, 8, ?\n다음 숫자는? (숫자만 입력)',
		answer: '10',
		hint: '짝수가 2씩 증가합니다.',
		type: '관찰',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 28,
		title: '자리 바꾸기',
		question: '[서재의 기록]\n암호 규칙: 각 알파벳을 바로 다음 알파벳으로 바꾼다.\n"HOUSE"를 이 규칙으로 암호화하면? (대문자 5글자)',
		answer: 'IPVTF',
		hint: 'H->I, O->P, U->V, S->T, E->F',
		type: '암호',
		difficulty: 3,
	},
	{
		id: 29,
		title: '정원의 오각형 분수',
		question: '[정원의 기록]\n오각형 모양 분수의 변은 몇 개인가? (숫자만 입력)',
		answer: '5',
		hint: '오각형입니다.',
		type: '도형',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 30,
		title: '최종 문장',
		question: '[응접실의 기록]\n응접실 바닥에 흩어진 문장 조각들을 순서대로 탭하시오.',
		answer: '저택에서탈출성공했다',
		hint: '주어-목적어-서술어 순서를 생각해보세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['저택에서', '탈출', '성공했다'],
	},
	// ==========================================
	// Level 2 (20대 / 중학교 1학년 수준) — 방 31~60
	// ==========================================
	{
		id: 31,
		title: '저택 관리비',
		question: '[사무실의 기록]\n이번 달 관리비는 지난달의 1.5배이다.\n지난달 관리비가 40만원이었다면 이번 달은 얼마인가? (숫자만 입력, 만원 단위)',
		answer: '60',
		hint: '40 x 1.5',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 32,
		title: '일차식 자물쇠',
		question: '[서재의 기록]\n자물쇠 다이얼 규칙: 2x + 3 = 15.\nx의 값은? (숫자만 입력)',
		answer: '6',
		hint: '양변에서 3을 빼고 2로 나누세요.',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 33,
		title: '그림자 비율',
		question: '[탑의 기록]\n저택 첨탑의 그림자는 실제 높이의 2배로 늘어난다.\n첨탑 높이가 15m라면 그림자 길이는? (숫자만 입력)',
		answer: '30',
		hint: '15 x 2',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 34,
		title: '시저의 열쇠',
		question: '[서재의 기록]\n암호문 "PHHW"는 알파벳을 +3 이동해 만든 것이다.\n원문은? (대문자 4글자)',
		answer: 'MEET',
		hint: '각 글자를 -3 이동하세요.',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 35,
		title: '요리사의 메모',
		question: '[부엌의 기록]\n요리사가 남긴 글자 조각들을 순서대로 탭하면 "조리법"을 뜻하는 단어가 된다.',
		answer: 'RECIPE',
		hint: '요리법을 뜻하는 영어 단어입니다.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['R', 'E', 'C', 'I', 'P', 'E'],
	},
	{
		id: 36,
		title: '정원의 화분',
		question: '[정원의 기록]\n화분이 깨졌다. 세 사람 중 정확히 한 명만 진실을 말한다.\nA: "나는 안 깼다."\nB: "나도 안 깼다."\nC: "A가 깼다."\n범인은 누구인가? (A/B/C 중 입력)',
		answer: 'B',
		hint: '각자 진실이라고 가정했을 때 모순이 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 37,
		title: '액자 비율',
		question: '[서재의 기록]\n액자의 가로세로 비율은 3:2이다.\n가로가 18cm라면 세로는 몇 cm인가? (숫자만 입력)',
		answer: '12',
		hint: '18 / 3 x 2',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 38,
		title: '복도의 마름모',
		question: '[복도의 기록]\n마름모 타일 한 변이 5cm이다.\n네 변의 길이 합(둘레)은? (숫자만 입력)',
		answer: '20',
		hint: '5 x 4',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 39,
		title: '밀 수 없는 문',
		question: '[현관의 기록]\n저택의 어떤 문은 아무리 힘을 줘도 절대 밀리지 않는다.\n문에는 "당기시오"라고 적혀 있었다.\n이 문을 여는 방법은? (민다/당긴다/부순다 중 입력)',
		answer: '당긴다',
		hint: '문에 적힌 글자를 다시 읽어보세요.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 40,
		title: '이진수 자물쇠',
		question: '[지하실의 기록]\n이진수 1101은 십진수로 얼마인가? (숫자만 입력)',
		answer: '13',
		hint: '8 + 4 + 0 + 1',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 41,
		title: '촛불 소모량',
		question: '[보관실의 기록]\n양초 하나가 1시간에 2cm씩 녹는다. 처음 길이가 20cm였다면\n6시간 후 남은 길이는? (숫자만 입력)',
		answer: '8',
		hint: '20 - 2 x 6',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 42,
		title: '격자 속 규칙',
		question: '[다락방의 기록]\n1, 4, 9, 16, ?\n다음 수는 무엇인가? (숫자만 입력)',
		answer: '25',
		hint: '1², 2², 3², 4², 5²',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 43,
		title: '손님 명단',
		question: '[응접실의 기록]\n찢어진 손님 명단 조각: 백작, 자작, 남작.\n신분이 높은 순서대로 탭하시오.',
		answer: '백작자작남작',
		hint: '귀족 작위는 공작-후작-백작-자작-남작 순서입니다.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['백작', '자작', '남작'],
	},
	{
		id: 44,
		title: '서재의 도난',
		question: '[서재의 기록]\n서재에서 책이 사라졌다. 세 사람 중 정확히 한 명만 진실을 말한다.\n집사: "나는 안 가져갔다."\n하녀: "나도 안 가져갔다."\n손님: "집사가 가져갔다."\n범인은 누구인가? (집사/하녀/손님 중 입력)',
		answer: '하녀',
		hint: '각자 진실이라고 가정했을 때 모순이 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 45,
		title: '환전 계산',
		question: '[사무실의 기록]\n1달러가 1300원일 때, 5달러는 몇 원인가? (숫자만 입력)',
		answer: '6500',
		hint: '1300 x 5',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 46,
		title: '정원 화단의 넓이',
		question: '[정원의 기록]\n밑변 8, 높이 5인 삼각형 화단의 넓이는? (숫자만 입력)',
		answer: '20',
		hint: '(8 x 5) / 2',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 47,
		title: '숫자로 바뀐 이름',
		question: '[서재의 기록]\n규칙: A=1, B=2, ... Z=26.\n"BED"의 알파벳 값을 모두 더하면? (숫자만 입력)',
		answer: '11',
		hint: 'B=2, E=5, D=4의 합',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 48,
		title: '수열 조각',
		question: '[다락방의 기록]\n흩어진 숫자 조각 8, 2, 6, 4를 오름차순으로 탭하시오.',
		answer: '2468',
		hint: '작은 수부터 고르세요.',
		type: '타일배열',
		difficulty: 1,
		inputType: 'tile-order',
		tiles: ['2', '4', '6', '8'],
	},
	{
		id: 49,
		title: '일꾼들의 품삯',
		question: '[사무실의 기록]\n일꾼 한 명의 하루 품삯은 15000원이다.\n일꾼 4명이 3일 일하면 총 품삯은? (숫자만 입력)',
		answer: '180000',
		hint: '15000 x 4 x 3',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 50,
		title: '벽시계의 눈금',
		question: '[탑의 기록]\n시계 눈금은 12개다. 3시간이 지나면 몇 개의 눈금을 지나는가? (숫자만 입력)',
		answer: '15',
		hint: '1시간에 5칸씩 움직입니다.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 51,
		title: '빛이 없는 방',
		question: '[지하실의 기록]\n창문이 없는 방에 촛불을 하나만 켰다.\n촛불을 끄면 방 안은 무엇으로 가득할까? (어둠/공기/먼지 중 입력)',
		answer: '어둠',
		hint: '빛이 없으면 남는 것입니다.',
		type: '넌센스',
		difficulty: 1,
	},
	{
		id: 52,
		title: '3의 배수 자물쇠',
		question: '[지하실의 기록]\n금고 다이얼은 3으로 나누어 떨어지는 수에서만 열린다.\n다음 중 열리는 수는? 22, 27, 31 (숫자만 입력)',
		answer: '27',
		hint: '27 / 3 = 9',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 53,
		title: '촛농 무게',
		question: '[보관실의 기록]\n초 하나의 무게가 120g이다. 촛농이 녹아 무게의 1/4이 줄었다면\n남은 무게는? (숫자만 입력)',
		answer: '90',
		hint: '120 - 30',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 54,
		title: '육각 정자',
		question: '[정원의 기록]\n정육각형 정자의 내각 하나의 크기는? (숫자만 입력, 도 단위)',
		answer: '120',
		hint: '(6-2) x 180 / 6',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 55,
		title: '편지의 문장',
		question: '[서재의 기록]\n편지 조각 "열쇠는", "서재", "책장", "뒤에", "있다"를\n올바른 문장 순서로 탭하시오.',
		answer: '열쇠는서재책장뒤에있다',
		hint: '주어부터 순서대로 읽어보세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['열쇠는', '서재', '책장', '뒤에', '있다'],
	},
	{
		id: 56,
		title: '마구간의 열쇠',
		question: '[마구간의 기록]\n마구간 열쇠를 아무도 인정하지 않는다. 세 사람 중 정확히 한 명만 진실을 말한다.\n마부: "나는 안 가지고 있다."\n집사: "나도 안 가지고 있다."\n하녀: "마부가 가지고 있다."\n열쇠를 가진 사람은? (마부/집사/하녀 중 입력)',
		answer: '집사',
		hint: '각자 진실이라고 가정했을 때 모순이 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 3,
	},
	{
		id: 57,
		title: '탑의 계단 수',
		question: '[탑의 기록]\n탑 계단은 한 층에 18개씩이다.\n5개 층을 오르면 계단은 모두 몇 개인가? (숫자만 입력)',
		answer: '90',
		hint: '18 x 5',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 58,
		title: '달빛 각도',
		question: '[탑의 기록]\n달빛이 창문에 45도로 들어온다. 반사되어 나가는 각도도 45도라면,\n입사각과 반사각의 합은? (숫자만 입력)',
		answer: '90',
		hint: '45 + 45',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 59,
		title: '거꾸로 된 단어',
		question: '[서재의 기록]\n벽난로 위에 "MANTLE"이라 적힌 팻말이 있다.\n이 단어의 마지막 3글자를 순서대로 입력하시오. (대문자 3글자)',
		answer: 'TLE',
		hint: '뒤에서 3글자를 세어보세요: M-A-N-T-L-E',
		type: '암호',
		difficulty: 2,
	},
	{
		id: 60,
		title: '최종 계산',
		question: '[사무실의 기록]\n15 x 4 - 20 = ? (숫자만 입력)',
		answer: '40',
		hint: '60 - 20',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},

	// ==========================================
	// Level 3 (30대 / 중학교 2학년 수준) — 방 61~90
	// ==========================================
	{
		id: 61,
		title: '연립방정식 금고',
		question: '[지하실의 기록]\n금고 다이얼: x + y = 12, x - y = 4.\nx의 값은? (숫자만 입력)',
		answer: '8',
		hint: '두 식을 더하면 2x = 16',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 62,
		title: '그림자의 함수',
		question: '[정원의 기록]\n그림자 길이(cm) = 물체 높이(cm) x 1.5.\n높이 20cm인 촛대의 그림자는? (숫자만 입력)',
		answer: '30',
		hint: '20 x 1.5',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 63,
		title: '진법 변환 자물쇠',
		question: '[지하실의 기록]\n8진수 17은 10진수로 얼마인가? (숫자만 입력)',
		answer: '15',
		hint: '1 x 8 + 7',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 64,
		title: '가문의 문장',
		question: '[응접실의 기록]\n가문 문장에 새겨진 글자 조각을 탭한 순서가\n"성(castle)"을 뜻하는 단어가 되게 하시오.',
		answer: 'CASTLE',
		hint: '성을 뜻하는 영어 단어입니다.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['C', 'A', 'S', 'T', 'L', 'E'],
	},
	{
		id: 65,
		title: '네 명의 하인과 촛대',
		question: '[보관실의 기록]\n촛대가 사라졌다. 네 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "A가 범인이다."\n범인은 누구인가? (A/B/C/D 중 입력)',
		answer: 'A',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	{
		id: 66,
		title: '확률 주사위',
		question: '[응접실의 기록]\n주사위를 던져 짝수가 나올 확률을 기약분수로 나타낼 때\n분모는 얼마인가? (숫자만 입력)',
		answer: '2',
		hint: '짝수는 2,4,6으로 3/6 = 1/2',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 67,
		title: '피타고라스의 정원',
		question: '[정원의 기록]\n직각삼각형의 두 변이 9, 12일 때 빗변의 길이는? (숫자만 입력)',
		answer: '15',
		hint: '3-4-5 비율의 3배입니다.',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 68,
		title: '이차 규칙',
		question: '[다락방의 기록]\n1, 4, 9, 16, 25, ?\n다음 수는? (숫자만 입력)',
		answer: '36',
		hint: '6의 제곱입니다.',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 69,
		title: '모듈러 자물쇠',
		question: '[지하실의 기록]\n규칙: N을 7로 나눈 나머지. 23의 나머지는? (숫자만 입력)',
		answer: '2',
		hint: '21 + 2',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 70,
		title: '연도의 순서',
		question: '[서재의 기록]\n저택 증축 연도 조각 1902, 1888, 1935, 1911을\n오래된 순서대로 탭하시오.',
		answer: '1888190219111935',
		hint: '작은 숫자부터 고르세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['1888', '1902', '1911', '1935'],
	},
	{
		id: 71,
		title: '퍼센트 할인',
		question: '[사무실의 기록]\n골동품 가격 80000원에서 25% 할인하면 얼마인가? (숫자만 입력)',
		answer: '60000',
		hint: '80000 x 0.75',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 72,
		title: '오각별의 각',
		question: '[탑의 기록]\n정오각형의 내각의 합은? (숫자만 입력, 도 단위)',
		answer: '540',
		hint: '(5-2) x 180',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 73,
		title: '다섯 손님의 진술',
		question: '[응접실의 기록]\n보석이 사라졌다. 다섯 손님 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "C가 범인이다."\n범인은 누구인가? (A/B/C/D/E 중 입력)',
		answer: 'C',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	{
		id: 74,
		title: '알파벳 곱셈 암호',
		question: '[서재의 기록]\n규칙: 알파벳 순서 x2. C(3번째)는 어떤 수로 바뀌는가? (숫자만 입력)',
		answer: '6',
		hint: '3 x 2',
		type: '암호',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 75,
		title: '속력 계산',
		question: '[마구간의 기록]\n마차가 60km를 4시간 동안 이동했다.\n시속은 몇 km인가? (숫자만 입력)',
		answer: '15',
		hint: '60 / 4',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 76,
		title: '암호 조각 재배열',
		question: '[지하실의 기록]\n금고에 적힌 조각 3, 9, 1, 7, 5를 오름차순으로 탭하시오.',
		answer: '13579',
		hint: '작은 수부터 고르세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['1', '3', '5', '7', '9'],
	},
	{
		id: 77,
		title: '원기둥 창고',
		question: '[보관실의 기록]\n원의 지름이 14일 때 반지름은? (숫자만 입력)',
		answer: '7',
		hint: '지름 / 2',
		type: '도형',
		difficulty: 1,
		inputType: 'number',
	},
	{
		id: 78,
		title: '패턴 찾기',
		question: '[다락방의 기록]\n3, 6, 12, 24, 48, ?\n다음 수는? (숫자만 입력)',
		answer: '96',
		hint: '2배씩 증가합니다.',
		type: '관찰',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 79,
		title: '시저 -2 암호',
		question: '[서재의 기록]\n"FMSQC"는 원문의 각 글자를 알파벳 순서로 2칸 뒤로 이동해 만든 암호다.\n원문은? (대문자 5글자)',
		answer: 'HOUSE',
		hint: '각 글자를 +2 이동하세요.',
		type: '암호',
		difficulty: 3,
	},
	{
		id: 80,
		title: '무게 중심',
		question: '[보관실의 기록]\n저울 왼쪽에 3kg추 두 개, 오른쪽에 2kg추 세 개가 있다.\n양쪽 무게 차이는? (숫자만 입력)',
		answer: '0',
		hint: '3 x 2 = 6, 2 x 3 = 6, 차이는 0',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 81,
		title: '여섯 용의자',
		question: '[지하실의 기록]\n금괴가 사라졌다. 여섯 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "D가 범인이다."\n범인은 누구인가? (A~F 중 입력)',
		answer: 'D',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	{
		id: 82,
		title: '탑의 높이',
		question: '[탑의 기록]\n탑 그림자 길이가 24m이고, 그림자와 높이의 비율이 4:3이다(그림자:높이).\n탑의 높이는? (숫자만 입력)',
		answer: '18',
		hint: '24 / 4 x 3',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 83,
		title: '고서의 목차',
		question: '[서재의 기록]\n고서 목차 조각 "결말", "서론", "전개", "위기"를\n이야기 순서대로 탭하시오.',
		answer: '서론전개위기결말',
		hint: '이야기 구조를 떠올려 보세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['서론', '전개', '위기', '결말'],
	},
	{
		id: 84,
		title: '이자 계산',
		question: '[사무실의 기록]\n원금 10만원에 연 5% 단리 이자를 2년간 받으면 이자 총액은? (숫자만 입력)',
		answer: '10000',
		hint: '100000 x 0.05 x 2',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 85,
		title: '숨은 배수',
		question: '[다락방의 기록]\n1부터 30까지 수 중 4와 6의 공배수는 몇 개인가? (숫자만 입력)',
		answer: '2',
		hint: '12의 배수: 12, 24',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 86,
		title: '이진 자물쇠 2',
		question: '[지하실의 기록]\n10진수 26을 2진수로 바꾸면? (숫자만 입력, 이진수 그대로)',
		answer: '11010',
		hint: '16 + 8 + 2',
		type: '암호',
		difficulty: 3,
	},
	{
		id: 87,
		title: '부채꼴의 각',
		question: '[탑의 기록]\n원의 1/4에 해당하는 부채꼴의 중심각은? (숫자만 입력, 도 단위)',
		answer: '90',
		hint: '360 / 4',
		type: '도형',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 88,
		title: '재판정의 순서',
		question: '[응접실의 기록]\n재판 절차 조각 "판결", "증언", "기소", "변론"을\n진행되는 순서대로 탭하시오.',
		answer: '기소증언변론판결',
		hint: '재판이 시작되고 끝나는 순서를 생각해보세요.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['기소', '증언', '변론', '판결'],
	},
	{
		id: 89,
		title: '최종 방정식',
		question: '[사무실의 기록]\n3x - 5 = 16.\nx의 값은? (숫자만 입력)',
		answer: '7',
		hint: '21 / 3',
		type: '연산',
		difficulty: 2,
		inputType: 'number',
	},
	{
		id: 90,
		title: '최종 용의자',
		question: '[지하실의 기록]\n저택의 마지막 사건. 일곱 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "나는 범인이 아니다."\nG: "A가 범인이다."\n범인은 누구인가? (A~G 중 입력)',
		answer: 'A',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	// ==========================================
	// Level 4 (40대 이상 / 중학교 3학년 수준) — 방 91~120
	// ==========================================
	{
		id: 91,
		title: '인수분해 자물쇠',
		question: '[지하실의 기록]\nx² - 5x + 6 = 0의 두 해 중 더 큰 값은? (숫자만 입력)',
		answer: '3',
		hint: '(x-2)(x-3) = 0',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 92,
		title: '피타고라스 응용',
		question: '[정원의 기록]\n직각삼각형의 빗변이 13, 한 변이 5일 때 나머지 한 변은? (숫자만 입력)',
		answer: '12',
		hint: '5-12-13 비율입니다.',
		type: '도형',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 93,
		title: '모듈러 응용',
		question: '[지하실의 기록]\n규칙: (3N+1)을 5로 나눈 나머지. N=7일 때 값은? (숫자만 입력)',
		answer: '2',
		hint: '3 x 7 + 1 = 22, 22를 5로 나눈 나머지',
		type: '암호',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 94,
		title: '삼차 수열',
		question: '[다락방의 기록]\n1, 8, 27, 64, ?\n다음 수는? (숫자만 입력)',
		answer: '125',
		hint: '5의 세제곱입니다.',
		type: '관찰',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 95,
		title: '암호 알고리즘 조각',
		question: '[서재의 기록]\n암호 절차 조각 "암호화", "평문", "전송", "복호화"를\n올바른 처리 순서로 탭하시오.',
		answer: '평문암호화전송복호화',
		hint: '메시지가 만들어지고 전달되는 순서를 생각해보세요.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['평문', '암호화', '전송', '복호화'],
	},
	{
		id: 96,
		title: '거울 속 초상화',
		question: '[응접실의 기록]\n초상화 속 인물은 거울을 보고 있지만 자신의 얼굴이 보이지 않는다고 한다.\n왜일까? (그림이라서/눈을감아서/거울이깨져서 중 입력)',
		answer: '그림이라서',
		hint: '초상화 속 인물은 실제로 보는 행위를 할 수 없습니다.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 97,
		title: '복리 이자',
		question: '[사무실의 기록]\n원금 10만원을 연 10% 복리로 2년간 예치하면 원리금 합계는? (숫자만 입력)',
		answer: '121000',
		hint: '100000 x 1.1 x 1.1',
		type: '연산',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 98,
		title: '삼각형의 닮음',
		question: '[서재의 기록]\n닮음비가 1:3인 두 삼각형에서 작은 삼각형 넓이가 4일 때\n큰 삼각형 넓이는? (숫자만 입력)',
		answer: '36',
		hint: '넓이비는 (1:3)² = 1:9',
		type: '도형',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 99,
		title: '깨지지 않는 접시',
		question: '[부엌의 기록]\n접시를 2층 창문에서 던져도 깨지지 않았다. 왜일까? (1층에서던져서/창문이닫혀있어서/고무접시라서 중 입력)',
		answer: '1층에서던져서',
		hint: '"2층에서 떨어뜨렸다"고 하지 않았습니다. 던진 방향을 다시 생각해보세요.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 100,
		title: '긴 암호 문장',
		question: '[지하실의 기록]\n조각난 문장 "지하실에", "숨겨진", "금고의", "열쇠가", "있다"를\n올바른 문장 순서로 탭하시오.',
		answer: '지하실에숨겨진금고의열쇠가있다',
		hint: '장소-수식어-목적어-서술어 순서를 생각해보세요.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['지하실에', '숨겨진', '금고의', '열쇠가', '있다'],
	},
	{
		id: 101,
		title: '피보나치 저택',
		question: '[다락방의 기록]\n1, 1, 2, 3, 5, 8, ?\n다음 수는? (숫자만 입력)',
		answer: '13',
		hint: '앞의 두 수를 더합니다.',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 102,
		title: '비례식 자물쇠',
		question: '[지하실의 기록]\nx:6 = 10:15 일 때 x의 값은? (숫자만 입력)',
		answer: '4',
		hint: '6 x 10 / 15',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 103,
		title: '다섯 용의자의 함정',
		question: '[응접실의 기록]\n은식기가 사라졌다. 다섯 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "B가 범인이다."\n범인은 누구인가? (A/B/C/D/E 중 입력)',
		answer: 'B',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	{
		id: 104,
		title: '저택의 마지막 진실',
		question: '[응접실의 기록]\n보물이 사라졌다. 여섯 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "C가 범인이다."\n범인은 누구인가? (A~F 중 입력)',
		answer: 'C',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 4,
	},
	{
		id: 105,
		title: '제곱근 자물쇠',
		question: '[지하실의 기록]\n169의 제곱근은? (숫자만 입력)',
		answer: '13',
		hint: '13 x 13 = 169',
		type: '암호',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 106,
		title: '농도 계산',
		question: '[부엌의 기록]\n소금물 200g에 소금이 20g 녹아 있다.\n농도는 몇 %인가? (숫자만 입력)',
		answer: '10',
		hint: '20 / 200 x 100',
		type: '연산',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 107,
		title: '최종 암호 배열',
		question: '[지하실의 기록]\n금고 다이얼 조각 5, 3, 8, 1, 9, 2를\n오름차순으로 탭하여 최종 암호를 만드시오.',
		answer: '123589',
		hint: '작은 수부터 고르세요.',
		type: '타일배열',
		difficulty: 2,
		inputType: 'tile-order',
		tiles: ['1', '2', '3', '5', '8', '9'],
	},
	{
		id: 108,
		title: '없어지지 않는 초',
		question: '[보관실의 기록]\n촛불 10개 중 2개가 바람에 꺼졌다. 잠시 후 다시 세어보니 촛불은 여전히 10개였다.\n어떻게 된 일일까? (다시켰다/꺼진게아니다/촛대를더가져왔다 중 입력)',
		answer: '다시켰다',
		hint: '꺼진 초를 그대로 둘 필요는 없습니다.',
		type: '넌센스',
		difficulty: 2,
	},
	{
		id: 109,
		title: '등비수열의 저택',
		question: '[다락방의 기록]\n2, 6, 18, 54, ?\n다음 수는? (숫자만 입력)',
		answer: '162',
		hint: '3배씩 증가합니다.',
		type: '관찰',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 110,
		title: '복합 모듈러',
		question: '[지하실의 기록]\n규칙: N을 4로 나눈 나머지에 3을 곱한다. N=15일 때 값은? (숫자만 입력)',
		answer: '9',
		hint: '15를 4로 나눈 나머지는 3, 3 x 3 = 9',
		type: '암호',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 111,
		title: '최종 방정식 2',
		question: '[사무실의 기록]\n2(x+3) = 16.\nx의 값은? (숫자만 입력)',
		answer: '5',
		hint: 'x + 3 = 8',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 112,
		title: '일곱 용의자의 함정',
		question: '[응접실의 기록]\n마지막 보석이 사라졌다. 일곱 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "나는 범인이 아니다."\nG: "D가 범인이다."\n범인은 누구인가? (A~G 중 입력)',
		answer: 'D',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 5,
	},
	{
		id: 113,
		title: '닮음 그림자',
		question: '[정원의 기록]\n실제 높이 6m인 조각상의 그림자가 4m이다.\n같은 시각 그림자 길이가 10m인 나무의 실제 높이는? (숫자만 입력)',
		answer: '15',
		hint: '6:4 = x:10',
		type: '도형',
		difficulty: 4,
		inputType: 'number',
	},
	{
		id: 114,
		title: '먼지 쌓인 시계',
		question: '[다락방의 기록]\n멈춘 지 오래된 시계가 있다. 하루에 시간이 정확히 두 번 맞는 시계는\n항상 움직이는 시계와 멈춘 시계 중 어느 쪽일까? (멈춘시계/움직이는시계 중 입력)',
		answer: '멈춘시계',
		hint: '조금씩 어긋나는 시계는 하루에 정확한 시각을 지나칠 뿐 정확히 멈추지 않습니다.',
		type: '넌센스',
		difficulty: 3,
	},
	{
		id: 115,
		title: '확률의 방',
		question: '[응접실의 기록]\n주머니에 빨간 공 3개, 파란 공 2개가 있다.\n빨간 공을 뽑을 확률을 기약분수로 나타낼 때 분모는? (숫자만 입력)',
		answer: '5',
		hint: '3/5',
		type: '연산',
		difficulty: 3,
		inputType: 'number',
	},
	{
		id: 116,
		title: '최종 문서 조각',
		question: '[서재의 기록]\n마지막 문서 조각 "저택의", "모든", "비밀이", "풀렸다"를\n올바른 문장 순서로 탭하시오.',
		answer: '저택의모든비밀이풀렸다',
		hint: '주어부터 순서대로 읽어보세요.',
		type: '타일배열',
		difficulty: 3,
		inputType: 'tile-order',
		tiles: ['저택의', '모든', '비밀이', '풀렸다'],
	},
	{
		id: 117,
		title: '두 개의 열쇠',
		question: '[현관의 기록]\n집사가 열쇠 두 개를 건넸다. 하나는 진짜, 하나는 가짜다.\n"가짜 열쇠는 항상 거짓말을 한다"는 쪽지가 있다. 열쇠가 말을 할 리 없는데도\n이 쪽지가 힌트가 되는 이유는 무엇일까? (쪽지자체가단서라서/열쇠가말한다/장난이다 중 입력)',
		answer: '쪽지자체가단서라서',
		hint: '열쇠가 말하는 게 아니라, 쪽지의 내용 자체가 논리 퍼즐의 설정입니다.',
		type: '넌센스',
		difficulty: 3,
	},
	{
		id: 118,
		title: '최종 규칙 찾기',
		question: '[다락방의 기록]\n2, 5, 11, 23, 47, ?\n다음 수는? (숫자만 입력)',
		answer: '95',
		hint: '각 항에 2를 곱하고 1을 더합니다.',
		type: '관찰',
		difficulty: 5,
		inputType: 'number',
	},
	{
		id: 119,
		title: '최종 모듈러 자물쇠',
		question: '[지하실의 기록]\n규칙: N²을 7로 나눈 나머지. N=10일 때 값은? (숫자만 입력)',
		answer: '2',
		hint: '10² = 100, 100을 7로 나눈 나머지',
		type: '암호',
		difficulty: 5,
		inputType: 'number',
	},
	{
		id: 120,
		title: '저택 최후의 진실',
		question: '[응접실의 기록]\n저택 탈출의 마지막 관문. 여덟 사람 중 정확히 한 명만 거짓말을 한다.\nA: "나는 범인이 아니다."\nB: "나는 범인이 아니다."\nC: "나는 범인이 아니다."\nD: "나는 범인이 아니다."\nE: "나는 범인이 아니다."\nF: "나는 범인이 아니다."\nG: "나는 범인이 아니다."\nH: "E가 범인이다."\n범인은 누구인가? (A~H 중 입력)',
		answer: 'E',
		hint: '각자 거짓말한다고 가정하고 모순 없는 경우를 찾아보세요.',
		type: '추리',
		difficulty: 5,
	},
];
