import { Room } from "@/types/room";
export const rooms: Room[] = [
  {
    id: 1,
    title: "숫자 규칙 추리",
    question: "2, 6, 12, 20, ?, 42",
    answer: "30",
    hint: "증가하는 간격에 주목해 보세요. 차이는 4, 6, 8...",
    type: "number_pattern",
    difficulty: 3,
  },
  {
    id: 2,
    title: "연관 퀴즈",
    question: "방을 잘 관찰해보세요!(답은 영어로 작성)",
    answer: "magic",
    hint: "어디에 사용하는 물건들이지?",
    type: "ox_quiz",
    difficulty: 4,
  },
  {
    id: 3,
    title: "순서 정렬",
    question:
      "다음 동물 중 다리가 가장 많은 동물은?: 문어], [개미], [거미], [게]",
    answer: "게",
    hint: "별다른 힌트는 없습니다.",
    type: "drag_sort",
    difficulty: 4.5,
  },
  {
    id: 4,
    title: "암호 해독",
    question: "ujhfs",
    answer: "tiger",
    hint: "각 알파벳의 이전 알파벳은???",
    type: "cipher",
    difficulty: 5,
  },
  {
    id: 5,
    title: "거울 문자 해독",
    question: "글자를 읽어보세요: ǝɟɟɐɹᴉƃ",
    answer: "giraffe",
    hint: "글자를 거울에 비춰보세요.",
    type: "mirror_text",
    difficulty: 5.5,
  },
  {
    id: 6,
    title: "이미지 해독",
    question: "방을 잘 관찰해보세요. 답은한글로..",
    answer: "프랑스",
    hint: "어떤 나라의 이름일까요?",
    type: "direction_sequence",
    difficulty: 6,
  },
  {
    id: 7,
    title: "그림 해독",
    question: "비밀번호 4자리를 찾아보세요.",
    answer: "1461",
    hint: "day",
    type: "image_difference",
    difficulty: 6.5,
  },
  {
    id: 8,
    title: "단어 조합",
    question: "trnapoeimuapn ??",
    answer: "tree",
    hint: "글자가 섞여 있습니다.",
    type: "word_unscramble",
    difficulty: 7.5,
  },
  {
    id: 9,
    title: "글자 자물쇠",
    question: "숫자를 찾고 글자를 찾아보세요.(영어3글자)",
    answer: "NOX",
    hint: "방의 모든 글자를 읽어보세요.",
    type: "number_lock",
    difficulty: 8.5,
  },
  {
    id: 10,
    title: "색깔 퍼즐",
    question: "🟥 = 3, 🟩🟩 = 8, 🟦 + 🟥 = 6. 암호는?",
    answer: "3434",
    hint: "색을 숫자로 바꾸고 조합해보세요.",
    type: "color_logic",
    difficulty: 10,
  },
];
